-- =====================================================================
-- Path to Apotheosis - Server bootstrap (Script Extender)
-- =====================================================================

-- =====================================================================
-- Centralised logging  (see CLAUDE.md "In-game debug feedback loop").
-- Output goes to the SE console (CreateConsole) AND the SE log file
-- (EnableLogging -> %LOCALAPPDATA%\...\Extender Logs\). Every line is
-- tagged [Apotheosis] so it is greppable in the log. Flip Apotheosis.DEBUG
-- to false to silence the verbose Debug() traces.
-- =====================================================================
local TAG = "[Apotheosis]"
Apotheosis = Apotheosis or {}
_G.Apotheosis = Apotheosis  -- expose to SE console REPL (mod env is isolated from REPL _G)
Apotheosis.DEBUG = false  -- verbose traces off for players; testers: `Apotheosis.DEBUG = true` in the SE console

local Log = {}
function Log.Info(...)  Ext.Utils.Print(TAG, ...) end
function Log.Warn(...)  Ext.Utils.PrintWarning(TAG, ...) end
function Log.Error(...) Ext.Utils.PrintError(TAG, ...) end
function Log.Debug(...) if Apotheosis.DEBUG then Ext.Utils.Print(TAG, "[dbg]", ...) end end
Apotheosis.Log = Log

Log.Info("BootstrapServer.lua loading - server context")

-- Heartbeat: confirm the mod actually reached a running session. If this line
-- never prints to the console, the mod is not being loaded (check deployment).
Ext.Events.SessionLoaded:Subscribe(function()
    local ok, err = pcall(function()
        Log.Info("SessionLoaded - Apotheosis server scripts active")
    end)
    if not ok then Log.Error("SessionLoaded heartbeat error: " .. tostring(err)) end
end)

-- =====================================================================
-- Diviner feature "Greater Portent" (PHB 2024, Wizard subclass, level 14):
-- you roll a THIRD Portent d20 each long rest (the base feature rolls two).
--
-- How the base game works (verified via Norbyte's Osiris dump):
--   The script GLO_Spells_PostEA reacts to LongRestFinished(), clears the old
--   Portent statuses and applies two fresh PORTENT_<value> statuses, where each
--   <value> (1..20) is the rolled die face. The count of dice is fixed at 2 and
--   is NOT exposed through any stat, action resource or progression, so a third
--   die cannot be added through Stats/Lsx data alone.
--
-- Our approach:
--   For any character that owns the marker passive Diviner_14_GreaterPortent,
--   we apply one ADDITIONAL random PORTENT_<value> shortly after the long rest
--   completes. The base game has already cleared + reapplied its two dice by
--   then, so there is no accumulation across rests.
-- =====================================================================

local GREATER_PORTENT_PASSIVE = "Diviner_14_GreaterPortent"

-- Delay so the base-game Portent reroll (clear + apply 2 dice) finishes first.
local APPLY_DELAY_MS = 1500

--- Roll a single d20. Prefer the Script Extender RNG (engine-seeded); fall back
--- to Lua's math.random if unavailable.
local function rollD20()
    if Ext.Random then
        return Ext.Random(1, 20)
    end
    return math.random(1, 20)
end

--- Grant one extra Portent die to a character that has Greater Portent.
local function grantExtraPortentDie(character)
    if not character then return end
    if Osi.HasPassive(character, GREATER_PORTENT_PASSIVE) == 1 then
        local value = rollD20()
        -- ApplyStatus(target, statusId, duration, force, source); -1 = permanent.
        Osi.ApplyStatus(character, "PORTENT_" .. value, -1.0, 1, character)
    end
end

-- Exposed so FeatureTests.lua can exercise the grant path directly.
Apotheosis.Features = Apotheosis.Features or {}
Apotheosis.Features.GrantExtraPortentDie = grantExtraPortentDie

-- =====================================================================
-- Level 7-9 spell riders (spells generated by
-- Scripts/generate_level79_spells.py; designs in docs/SPELLS-7-9.md).
--
-- Finger of Death: a humanoid killed while carrying the
-- APO_FINGER_OF_DEATH mark rises as a zombie serving the caster's side.
-- Clone: a character downed while carrying APO_CLONE is fully revived
-- once; the clone is consumed.
-- =====================================================================

local FINGER_OF_DEATH_MARK = "APO_FINGER_OF_DEATH"
local FINGER_ZOMBIE_TEMPLATE = "c2a2c269-ede8-4887-99f1-e0c044cc0c75" -- AnimateDead zombie
local HERO_FACTION = "a1542c81-6895-929e-4522-10ce218bb360"           -- Hero (fights for party)

Ext.Osiris.RegisterListener("Died", 1, "after", function(character)
    local ok, err = pcall(function()
        if Osi.HasActiveStatus(character, FINGER_OF_DEATH_MARK) ~= 1 then return end
        local x, y, z = Osi.GetPosition(character)
        if not x then return end
        local zombie = Osi.CreateAt(FINGER_ZOMBIE_TEMPLATE, x + 1, y, z + 1, 0, 0, "")
        if zombie and zombie ~= "" then
            pcall(Osi.SetFaction, zombie, HERO_FACTION)
            Log.Info("Finger of Death: " .. tostring(character) .. " rises as zombie " .. tostring(zombie))
        end
    end)
    if not ok then
        Log.Error("Finger of Death rider error: " .. tostring(err))
    end
end)

local CLONE_MARK = "APO_CLONE"

Ext.Osiris.RegisterListener("StatusApplied", 4, "after", function(object, status, _, _)
    local ok, err = pcall(function()
        if status ~= "DOWNED" then return end
        if Osi.HasActiveStatus(object, CLONE_MARK) ~= 1 then return end
        Osi.RemoveStatus(object, CLONE_MARK)
        Ext.Timer.WaitFor(300, function()
            local okRevive, errRevive = pcall(function()
                Osi.Resurrect(object)
                Log.Info("Clone: " .. tostring(object) .. " restored to full strength; clone consumed")
            end)
            if not okRevive then
                Log.Error("Clone revive error: " .. tostring(errRevive))
            end
        end)
    end)
    if not ok then
        Log.Error("Clone rider error: " .. tostring(err))
    end
end)

Ext.Osiris.RegisterListener("LongRestFinished", 0, "after", function()
    Ext.Timer.WaitFor(APPLY_DELAY_MS, function()
        local players = Osi.DB_Players:Get(nil)
        if not players then return end
        for _, row in pairs(players) do
            local ok, err = pcall(grantExtraPortentDie, row[1])
            if not ok then
                Ext.Utils.PrintError("[Apotheosis] Greater Portent error: " .. tostring(err))
            end
        end
    end)
end)

-- =====================================================================
-- Barbarian feature "Persistent Rage" (PHB 2024, level 15):
--   When you roll Initiative you regain all expended uses of Rage; once
--   per Long Rest. (The "Rage lasts 10 minutes" half is pure stats: the
--   passive keeps RAGE_STOP_REMOVE on the barbarian.)
-- Stats can't express "only if a use was spent", so it's scripted:
-- EnteredCombat -> if the passive is present, Rage < max and the
-- APO_PERSISTENT_RAGE_USED marker is absent, apply the refill status and
-- set the marker. LongRestFinished clears the marker.
-- =====================================================================
local PERSISTENT_RAGE_PASSIVE = "Barbarian_PersistentRage"
local PERSISTENT_RAGE_USED = "APO_PERSISTENT_RAGE_USED"
local PERSISTENT_RAGE_RESTORE = "APO_PERSISTENT_RAGE_RESTORE"
local rageResourceUUID = nil

local function getRageResourceUUID()
    if rageResourceUUID then return rageResourceUUID end
    for _, uuid in pairs(Ext.StaticData.GetAll("ActionResource")) do
        local res = Ext.StaticData.Get(uuid, "ActionResource")
        if res and res.Name == "Rage" then
            rageResourceUUID = uuid
            break
        end
    end
    return rageResourceUUID
end

--- Current and max Rage uses, or nil if the character has no Rage resource.
local function getRageUses(character)
    local uuid = getRageResourceUUID()
    local entity = Ext.Entity.Get(character)
    if not uuid or not entity or not entity.ActionResources then return nil end
    local entries = entity.ActionResources.Resources[uuid]
    if not entries or not entries[1] then return nil end
    return entries[1].Amount, entries[1].MaxAmount
end

--- Returns true if Rage was refilled, otherwise false plus the reason.
local function tryPersistentRage(character)
    if Osi.HasPassive(character, PERSISTENT_RAGE_PASSIVE) ~= 1 then return false, "no passive" end
    if Osi.HasActiveStatus(character, PERSISTENT_RAGE_USED) == 1 then return false, "already used this long rest" end
    local amount, max = getRageUses(character)
    if not amount then return false, "no Rage resource" end
    if amount >= max then return false, "no expended uses" end
    Osi.ApplyStatus(character, PERSISTENT_RAGE_RESTORE, 0, 1)
    Osi.ApplyStatus(character, PERSISTENT_RAGE_USED, -1, 1)
    Log.Info("Persistent Rage: " .. tostring(character) .. " regained Rage (" .. tostring(amount) .. "/" .. tostring(max) .. " -> full)")
    return true
end
Apotheosis.Features = Apotheosis.Features or {}
Apotheosis.Features.TryPersistentRage = tryPersistentRage
Apotheosis.Features.GetRageUses = getRageUses
Apotheosis.Features.GetRageResourceUUID = getRageResourceUUID

Ext.Osiris.RegisterListener("EnteredCombat", 2, "after", function(object, _)
    local ok, err = pcall(tryPersistentRage, object)
    if not ok then Log.Error("Persistent Rage error: " .. tostring(err)) end
end)

Ext.Osiris.RegisterListener("LongRestFinished", 0, "after", function()
    local ok, err = pcall(function()
        local players = Osi.DB_Players:Get(nil)
        if not players then return end
        for _, row in pairs(players) do
            if Osi.HasActiveStatus(row[1], PERSISTENT_RAGE_USED) == 1 then
                Osi.RemoveStatus(row[1], PERSISTENT_RAGE_USED)
            end
        end
    end)
    if not ok then Log.Error("Persistent Rage long-rest reset error: " .. tostring(err)) end
end)

-- =====================================================================
-- Enchanter feature "Alter Memories" - Modify Memory aura (PHB 2024,
-- Wizard subclass, level 14).
--
-- The spell Shout_Apotheosis_ModifyMemory applies MODIFY_MEMORY_AURA to the
-- caster: a 6m following, concentration aura that tags every valid enemy in
-- range with the technical marker MODIFY_MEMORY_MARK (applied/removed by the
-- engine as creatures enter/leave the radius).
--
-- BG3 auras have no native "max targets" field, so we enforce a TARGET CAP with
-- a FIFO queue here:
--   * cap = 1 normally, 2 if the caster owns Enchanter_14_AlterMemories.
--   * The first 'cap' enemies to enter are "active": each is locked down by an
--     even 50/50 split of MM_HOLD (Paralyzed) or MM_SLOW (Slowed).
--   * Extra enemies wait in a FIFO queue. When an active victim leaves the aura,
--     dies, or the aura ends (its mark is removed), the next queued enemy is
--     promoted in arrival order.
-- =====================================================================

local MM_PASSIVE   = "Enchanter_14_AlterMemories"
local MM_AURA      = "MODIFY_MEMORY_AURA"
local MM_MARK      = "MODIFY_MEMORY_MARK"
local MM_HOLD      = "MM_HOLD"
local MM_SLOW      = "MM_SLOW"

-- mmState[casterGuid] = { active = { [victimGuid] = effectStatus }, activeCount = N, queue = { victimGuid, ... } }
local mmState = {}

--- Target cap for a given caster: 2 with the feature, otherwise 1.
local function mmCap(caster)
    if Osi.HasPassive(caster, MM_PASSIVE) == 1 then
        return 2
    end
    return 1
end

local function mmGetState(caster)
    local st = mmState[caster]
    if not st then
        st = { active = {}, activeCount = 0, queue = {} }
        mmState[caster] = st
    end
    return st
end

--- Coin flip: true ~50% of the time (engine RNG preferred).
local function mmCoinFlip()
    if Ext.Random then
        return Ext.Random(0, 1) == 0
    end
    return math.random(0, 1) == 0
end

--- Lock a victim down with one of the two effects, recording which was applied.
local function mmActivate(caster, victim)
    local st = mmGetState(caster)
    if st.active[victim] then return end
    local status = mmCoinFlip() and MM_HOLD or MM_SLOW
    -- ApplyStatus(target, statusId, duration, force, source); -1 = SE-managed.
    Osi.ApplyStatus(victim, status, -1.0, 1, caster)
    st.active[victim] = status
    st.activeCount = st.activeCount + 1
end

--- Promote queued enemies into free slots, FIFO, skipping any that have since
--- left the aura or died.
local function mmPromote(caster)
    local st = mmState[caster]
    if not st then return end
    local cap = mmCap(caster)
    while st.activeCount < cap and #st.queue > 0 do
        local victim = table.remove(st.queue, 1)
        if Osi.HasActiveStatus(victim, MM_MARK) == 1 and Osi.IsDead(victim) == 0 then
            mmActivate(caster, victim)
        end
    end
end

--- Remove a victim's active effect (if any) and free its slot.
local function mmDeactivate(caster, victim)
    local st = mmState[caster]
    if not st then return end
    local effect = st.active[victim]
    if effect then
        Osi.RemoveStatus(victim, effect)
        st.active[victim] = nil
        st.activeCount = st.activeCount - 1
    end
end

--- An enemy entered the aura: activate immediately if a slot is free, else queue.
local function mmOnMarkApplied(victim, caster)
    if not caster or caster == "" then return end
    -- Only act for a genuine aura owner (filters out any unrelated causee).
    if Osi.HasActiveStatus(caster, MM_AURA) ~= 1 then return end
    local st = mmGetState(caster)
    if st.active[victim] then return end
    for _, v in ipairs(st.queue) do
        if v == victim then return end
    end
    if st.activeCount < mmCap(caster) then
        mmActivate(caster, victim)
    else
        st.queue[#st.queue + 1] = victim
    end
end

--- An enemy left the aura (or the aura ended): free its slot/queue position and
--- promote the next enemy in line.
local function mmOnMarkRemoved(victim, caster)
    local st = caster and caster ~= "" and mmState[caster] or nil
    if not st then return end
    if st.active[victim] then
        mmDeactivate(caster, victim)
        mmPromote(caster)
    else
        for i, v in ipairs(st.queue) do
            if v == victim then
                table.remove(st.queue, i)
                break
            end
        end
    end
end

--- The aura ended on the caster: clear every active effect and reset state.
local function mmOnAuraRemoved(caster)
    local st = mmState[caster]
    if not st then return end
    for victim, effect in pairs(st.active) do
        Osi.RemoveStatus(victim, effect)
    end
    mmState[caster] = nil
end

-- StatusApplied(object, status, causee, storyActionID): causee is the aura owner.
Ext.Osiris.RegisterListener("StatusApplied", 4, "after", function(object, status, causee, _)
    if status ~= MM_MARK then return end
    local ok, err = pcall(mmOnMarkApplied, object, causee)
    if not ok then
        Ext.Utils.PrintError("[Apotheosis] Modify Memory (apply) error: " .. tostring(err))
    end
end)

-- StatusRemoved(object, status, causee, applyStoryActionID).
Ext.Osiris.RegisterListener("StatusRemoved", 4, "after", function(object, status, causee, _)
    if status == MM_MARK then
        local ok, err = pcall(mmOnMarkRemoved, object, causee)
        if not ok then
            Ext.Utils.PrintError("[Apotheosis] Modify Memory (remove) error: " .. tostring(err))
        end
    elseif status == MM_AURA then
        local ok, err = pcall(mmOnAuraRemoved, object)
        if not ok then
            Ext.Utils.PrintError("[Apotheosis] Modify Memory (aura end) error: " .. tostring(err))
        end
    end
end)

-- =====================================================================
-- Celestial feature "Searing Vengeance" (PHB 2024, Warlock subclass,
-- level 14) - heal to HALF YOUR HIT POINT MAXIMUM.
--
-- The stat side (SEARING_VENGEANCE_DOWNED) guarantees survival with a 1 HP
-- floor and fires the radiant burst. The engine's RegainHitPoints functor
-- can't express "half of max HP", so once the custom downed status lands we
-- top the warlock up to half their maximum here. We only ever RAISE current
-- HP, so the 1 HP floor is never undone if half-max happens to be lower.
-- =====================================================================

local SEARING_DOWNED = "SEARING_VENGEANCE_DOWNED"

local function searingHealHalf(character)
    local entity = Ext.Entity.Get(character)
    if not entity or not entity.Health then return end
    local health = entity.Health
    local maxHp = health.MaxHp or 0
    if maxHp <= 0 then return end
    local half = math.floor(maxHp / 2)
    if health.Hp < half then
        health.Hp = half
        entity:Replicate("Health")
    end
end

Ext.Osiris.RegisterListener("StatusApplied", 4, "after", function(object, status, _, _)
    if status ~= SEARING_DOWNED then return end
    local ok, err = pcall(searingHealHalf, object)
    if not ok then
        Ext.Utils.PrintError("[Apotheosis] Searing Vengeance error: " .. tostring(err))
    end
end)

-- =====================================================================
-- Archfey feature "Bewitching Magic" (PHB 2024, Warlock subclass, level
-- 14) - add your CHARISMA MODIFIER to your spell save DC.
--
-- SpellSaveDC stat boosts only accept a literal integer, so we size the
-- bonus to the caster's Charisma here. The BEWITCHING_MAGIC status (applied
-- by the passive whenever an Enchantment/Illusion spell is cast) drives the
-- 2-turn lifetime: we add a SpellSaveDC boost when it lands and strip it
-- again when it ends. Refreshing the status never stacks the boost.
-- =====================================================================

local BEWITCH_STATUS = "BEWITCHING_MAGIC"
-- bewitchBoost[charGuid] = the exact boost string currently applied to it.
local bewitchBoost = {}

--- Charisma modifier of a character. Stats.Abilities is 1-indexed with [1]=None,
--- so Charisma (the 6th ability) is the 7th entry. Returns nil if unreadable.
local function charismaModifier(character)
    local entity = Ext.Entity.Get(character)
    if entity and entity.Stats and entity.Stats.Abilities then
        local score = entity.Stats.Abilities[7]
        if score then
            return math.floor((score - 10) / 2)
        end
    end
    return nil
end

local function bewitchApply(character)
    if bewitchBoost[character] then return end -- already boosted; don't stack on refresh
    local mod = charismaModifier(character)
    if not mod or mod <= 0 then return end
    local boost = "SpellSaveDC(" .. mod .. ")"
    -- AddBoosts(object, boosts, sourceType, cause).
    Osi.AddBoosts(character, boost, BEWITCH_STATUS, character)
    bewitchBoost[character] = boost
end

local function bewitchRemove(character)
    local boost = bewitchBoost[character]
    if not boost then return end
    -- RemoveBoosts(object, boosts, removeAll, sourceType, cause).
    Osi.RemoveBoosts(character, boost, 0, BEWITCH_STATUS, character)
    bewitchBoost[character] = nil
end

Ext.Osiris.RegisterListener("StatusApplied", 4, "after", function(object, status, _, _)
    if status ~= BEWITCH_STATUS then return end
    local ok, err = pcall(bewitchApply, object)
    if not ok then
        Ext.Utils.PrintError("[Apotheosis] Bewitching Magic (apply) error: " .. tostring(err))
    end
end)

Ext.Osiris.RegisterListener("StatusRemoved", 4, "after", function(object, status, _, _)
    if status ~= BEWITCH_STATUS then return end
    local ok, err = pcall(bewitchRemove, object)
    if not ok then
        Ext.Utils.PrintError("[Apotheosis] Bewitching Magic (remove) error: " .. tostring(err))
    end
end)

-- =====================================================================
-- Genie Sorcery feature "Elemental Rebuke" (Sorcerer subclass, level 15):
-- when a creature damages you with an attack, a burst of elemental energy
-- automatically strikes it.
--
-- Why Script Extender: the stat engine has no reactive "when hit, damage the
-- attacker" functor for a passive (interrupts aside). We listen to the Osiris
-- AttackedBy event (arity 7: defender, attackerOwner, attacker, damageType,
-- damageAmount, damageCause, storyActionID) and, if the defender owns the marker
-- passive, apply ELEMENTAL_REBUKE_HIT to the attacker. That status's
-- OnApplyFunctors deal the retaliation damage; StackType Overwrite lets it
-- re-trigger on every incoming hit.
-- =====================================================================

local ELEMENTAL_REBUKE_PASSIVE = "NobleGenies_15_ElementalRebuke"
local ELEMENTAL_REBUKE_HIT = "ELEMENTAL_REBUKE_HIT"

Ext.Osiris.RegisterListener("AttackedBy", 7, "after", function(defender, attackerOwner, attacker, damageType, damageAmount, damageCause, storyActionID)
    local ok, err = pcall(function()
        if not defender or not attacker or attacker == "" then return end
        if attacker == defender then return end
        if (tonumber(damageAmount) or 0) <= 0 then return end
        if Osi.HasPassive(defender, ELEMENTAL_REBUKE_PASSIVE) ~= 1 then return end
        if Osi.IsDead(defender) == 1 then return end
        -- Lash back: ELEMENTAL_REBUKE_HIT deals the damage on apply to the bearer.
        -- duration 6.0s = 1 turn; force = 1; source = the rebuking sorcerer.
        Osi.ApplyStatus(attacker, ELEMENTAL_REBUKE_HIT, 6.0, 1, defender)
    end)
    if not ok then
        Ext.Utils.PrintError("[Apotheosis] Elemental Rebuke error: " .. tostring(err))
    end
end)

-- =====================================================================
-- Druid feature "Beast Spells" (PHB 2024, level 18) - LIMITED adaptation.
--
-- The literal feature ("cast your druid spells while in Wild Shape") can't be
-- expressed in Stats data: a shapeshifted druid is polymorphed into a beast
-- that owns no spellbook and no spell slots. As a pragmatic stand-in we grant a
-- curated set of SUPPORT spells (offense is already covered by the beast's own
-- attacks) plus a small pool of temporary spell slots to fuel them, whenever a
-- druid that owns the marker passive Druid_BeastSpells enters Wild Shape, and
-- strip everything again on revert.
--
-- WILDSHAPE_TECHNICAL is the engine's own marker status and lives on the SAME
-- entity GUID while shapeshifted, so StatusApplied / StatusRemoved give clean
-- transform / revert hooks. The engine restores the druid's pre-transform
-- resources on revert, so the temporary slots never leak into normal play; we
-- still revoke our grants explicitly for safety and to cover partial reverts.
-- =====================================================================

local BEAST_SPELLS_PASSIVE = "Druid_BeastSpells"
local BEAST_SPELLS_MARK    = "WILDSHAPE_TECHNICAL"

-- Curated support spells granted while in beast form.
local BEAST_SPELLS_GRANTED = {
    "Target_HealingWord",
    "Target_CureWounds",
    "Target_LesserRestoration",
    "Target_FaerieFire",
    "Target_Moonbeam",
}

-- Temporary slots to fuel the curated list: 2x level 1, 1x level 2.
local BEAST_SPELLS_SLOTS = "ActionResource(SpellSlot,2,1);ActionResource(SpellSlot,1,2)"

-- beastSpellsActive[charGuid] = true while spells/slots are granted to it.
local beastSpellsActive = {}

local function beastSpellsGrant(character)
    if beastSpellsActive[character] then return end -- already granted; don't stack
    if Osi.HasPassive(character, BEAST_SPELLS_PASSIVE) ~= 1 then return end
    for _, spell in ipairs(BEAST_SPELLS_GRANTED) do
        Osi.AddSpell(character, spell, 0, 0)
    end
    -- AddBoosts(object, boosts, sourceType, cause); cause/source = the marker status.
    Osi.AddBoosts(character, BEAST_SPELLS_SLOTS, BEAST_SPELLS_MARK, character)
    beastSpellsActive[character] = true
end

local function beastSpellsRevoke(character)
    if not beastSpellsActive[character] then return end
    for _, spell in ipairs(BEAST_SPELLS_GRANTED) do
        Osi.RemoveSpell(character, spell, 0)
    end
    -- RemoveBoosts(object, boosts, removeAll, sourceType, cause).
    Osi.RemoveBoosts(character, BEAST_SPELLS_SLOTS, 0, BEAST_SPELLS_MARK, character)
    beastSpellsActive[character] = nil
end

Ext.Osiris.RegisterListener("StatusApplied", 4, "after", function(object, status, _, _)
    if status ~= BEAST_SPELLS_MARK then return end
    local ok, err = pcall(beastSpellsGrant, object)
    if not ok then
        Ext.Utils.PrintError("[Apotheosis] Beast Spells (grant) error: " .. tostring(err))
    end
end)

Ext.Osiris.RegisterListener("StatusRemoved", 4, "after", function(object, status, _, _)
    if status ~= BEAST_SPELLS_MARK then return end
    local ok, err = pcall(beastSpellsRevoke, object)
    if not ok then
        Ext.Utils.PrintError("[Apotheosis] Beast Spells (revoke) error: " .. tostring(err))
    end
end)

-- =====================================================================
-- Manual smoke driver.
--
-- Intended loop:
--   1. Start a fresh game / finish character creation.
--   2. Load into the world.
--   3. Open the Script Extender console and run: server
--   4. Trigger a smoke command such as: Apotheosis.Smoke.RunLevelSweep()
--
-- This is intentionally MANUAL-triggered, not auto-run. The driver can move
-- the host character through level checkpoints and run non-destructive checks.
-- Encounter-specific enemy/status orchestration is the next layer to add per
-- class/subclass plan.
-- =====================================================================

local function stringifyValue(value)
    if type(value) ~= "table" then
        return tostring(value)
    end

    local parts = {}
    for key, item in pairs(value) do
        parts[#parts + 1] = tostring(key) .. "=" .. stringifyValue(item)
    end
    table.sort(parts)
    return "{" .. table.concat(parts, ", ") .. "}"
end

local function getHostCharacterHandle()
    if Osi.GetHostCharacter then
        local host = Osi.GetHostCharacter()
        if host and host ~= "" then
            return host
        end
    end

    local players = Osi.DB_Players:Get(nil)
    if players then
        for _, row in pairs(players) do
            if row and row[1] and row[1] ~= "" then
                return row[1]
            end
        end
    end

    return nil
end

local Smoke = Apotheosis.Smoke or {}
Apotheosis.Smoke = Smoke

Smoke.Wizard = Smoke.Wizard or {}

Smoke.DEFAULT_START_LEVEL = 12
Smoke.DEFAULT_END_LEVEL = 20
Smoke.LEVEL_SETTLE_MS = 1200
Smoke.POST_RESTORE_SETTLE_MS = 600
Smoke.INTERACTIVE_POLL_MS = 1000
Smoke.INTERACTIVE_LEVEL_TIMEOUT_MS = 180000
Smoke.MARKER_PASSIVES = {
    "Barbarian_BrutalStrike_Improved",
    "Diviner_14_GreaterPortent",
    "Druid_BeastSpells",
    "Enchanter_14_AlterMemories",
    "NobleGenies_15_ElementalRebuke",
    "Rogue_SlipperyMind",
}

local smokeState = {
    running = false,
    lastHost = nil,
}

local function smokeDetectMarkers(character)
    local found = {}
    for _, passive in ipairs(Smoke.MARKER_PASSIVES) do
        if Osi.HasPassive(character, passive) == 1 then
            found[#found + 1] = passive
        end
    end
    return found
end

local function smokeGetHost()
    local host = getHostCharacterHandle()
    if not host then
        error("Smoke could not resolve a host character; load fully into the world first")
    end
    smokeState.lastHost = host
    return host
end

local function smokeRestore(character)
    if Osi.PROC_CharacterFullRestore then
        Osi.PROC_CharacterFullRestore(character)
    end
    if Osi.RemoveHarmfulStatuses then
        Osi.RemoveHarmfulStatuses(character)
    end
    if Osi.SetHitpointsPercentage then
        Osi.SetHitpointsPercentage(character, 100)
    end
end

local function smokeGetLevel(character)
    if not Osi.GetLevel then
        return nil
    end

    local ok, level = pcall(Osi.GetLevel, character)
    if not ok then
        return nil
    end

    return tonumber(level)
end

local function smokeTryAdvanceOneLevel(character, nextLevel)
    local beforeLevel = smokeGetLevel(character)

    if Osi.SetLevel then
        Osi.SetLevel(character, nextLevel)
        local afterSet = smokeGetLevel(character)
        if afterSet and afterSet >= nextLevel then
            return true, "SetLevel", beforeLevel, afterSet
        end
    end

    if Osi.PROC_LevelUpBy then
        Osi.PROC_LevelUpBy(character, 1)
        local afterBy = smokeGetLevel(character)
        if afterBy and afterBy >= nextLevel then
            return true, "PROC_LevelUpBy", beforeLevel, afterBy
        end
    end

    if Osi.PROC_LevelUp then
        Osi.PROC_LevelUp(character)
        local afterProc = smokeGetLevel(character)
        if afterProc and afterProc >= nextLevel then
            return true, "PROC_LevelUp", beforeLevel, afterProc
        end
    end

    return false, nil, beforeLevel, smokeGetLevel(character)
end

local function smokeSetLevel(character, level)
    local targetLevel = tonumber(level) or level
    local currentLevel = smokeGetLevel(character)
    if currentLevel and currentLevel >= targetLevel then
        return
    end

    if not currentLevel then
        if Osi.SetLevel then
            Osi.SetLevel(character, targetLevel)
            return
        end
        error("No available level-set API in this runtime")
    end

    Log.Info("Smoke level set requested: " .. tostring(currentLevel) .. " -> " .. tostring(targetLevel))

    for nextLevel = currentLevel + 1, targetLevel do
        local okStep, method, beforeStep, afterStep = smokeTryAdvanceOneLevel(character, nextLevel)
        if okStep then
            Log.Debug(
                "Smoke level step " .. tostring(beforeStep) .. " -> " .. tostring(afterStep) ..
                " via " .. tostring(method)
            )
        else
            Log.Warn(
                "Smoke level step blocked at " .. tostring(beforeStep) ..
                " while requesting " .. tostring(nextLevel) ..
                " (after=" .. tostring(afterStep) .. ")"
            )
            return
        end
    end

    local finalLevel = smokeGetLevel(character)
    if finalLevel and finalLevel >= targetLevel then
        return
    end

    Log.Warn("Smoke level set finished below target (target=" .. tostring(targetLevel) .. ", now=" .. tostring(finalLevel) .. ")")
end

local function smokeRunTimedLevelSequence(character, startAt, endAt, perLevel, onComplete)
    local function step(level)
        if level > endAt then
            if onComplete then
                onComplete()
            end
            return
        end

        smokeSetLevel(character, level)
        Log.Info("Smoke queued level " .. tostring(level) .. " - waiting for progression state to settle")

        Ext.Timer.WaitFor(Smoke.LEVEL_SETTLE_MS, function()
            smokeRestore(character)
            Ext.Timer.WaitFor(Smoke.POST_RESTORE_SETTLE_MS, function()
                perLevel(level)
                step(level + 1)
            end)
        end)
    end

    step(startAt)
end

local function smokeHasPassive(character, passive)
    return Osi.HasPassive(character, passive) == 1
end

local function smokeHasSpell(character, spell)
    if not Osi.HasSpell then
        return false
    end
    return Osi.HasSpell(character, spell, 0) == 1
end

local function smokeDescribeBuild(character)
    local tags = "<unavailable>"
    if Osi.CharacterGetTags then
        local ok, value = pcall(Osi.CharacterGetTags, character)
        if ok and value ~= nil then
            tags = value
        end
    end
    local markers = smokeDetectMarkers(character)
    Log.Info("Smoke host = " .. tostring(character))
    Log.Info("Smoke tags = " .. stringifyValue(tags))
    if #markers > 0 then
        Log.Info("Smoke tracked markers = " .. table.concat(markers, ", "))
    else
        Log.Info("Smoke tracked markers = <none>")
    end
end

local function smokeRunPassiveChecks(character, level)
    local markers = smokeDetectMarkers(character)
    Log.Info("Smoke level " .. tostring(level) .. " marker scan")
    if #markers == 0 then
        Log.Warn("Smoke level " .. tostring(level) .. ": no tracked marker passives found on host")
        return
    end

    for _, passive in ipairs(markers) do
        if Osi.HasPassive(character, passive) == 1 then
            Log.Info("Smoke PASS L" .. tostring(level) .. ": HasPassive(" .. passive .. ")")
        else
            Log.Error("Smoke FAIL L" .. tostring(level) .. ": missing passive " .. passive)
        end
    end
end

function Smoke.CaptureBuild()
    local ok, err = pcall(function()
        local host = smokeGetHost()
        smokeDescribeBuild(host)
    end)
    if not ok then
        Log.Error("Smoke.CaptureBuild error: " .. tostring(err))
    end
end

function Smoke.SetLevel(level)
    local ok, err = pcall(function()
        local host = smokeGetHost()
        smokeSetLevel(host, tonumber(level) or level)
        smokeRestore(host)
        Log.Info("Smoke moved host to level " .. tostring(level))
        smokeDescribeBuild(host)
    end)
    if not ok then
        Log.Error("Smoke.SetLevel error: " .. tostring(err))
    end
end

function Smoke.RunLevelSweep(startLevel, endLevel)
    local ok, err = pcall(function()
        if smokeState.running then
            error("Smoke run already in progress")
        end

        smokeState.running = true
        local host = smokeGetHost()
        local startAt = tonumber(startLevel) or Smoke.DEFAULT_START_LEVEL
        local endAt = tonumber(endLevel) or Smoke.DEFAULT_END_LEVEL

        Log.Info("Smoke level sweep starting: " .. tostring(startAt) .. " -> " .. tostring(endAt))
        smokeDescribeBuild(host)

        smokeRunTimedLevelSequence(host, startAt, endAt, function(level)
            Log.Info("Smoke reached level " .. tostring(level))
            smokeRunPassiveChecks(host, level)
        end, function()
            Log.Info("Smoke level sweep complete")
            Log.Info("Next step: add class/subclass-specific encounter hooks to Apotheosis.Smoke plans")
            smokeState.running = false
        end)
    end)
    if not ok then
        smokeState.running = false
        Log.Error("Smoke.RunLevelSweep error: " .. tostring(err))
    end
end

local WIZARD_LEVEL_EXPECTATIONS = {
    [12] = {
        absentPassives = { "SpellMastery", "Wizard_SignatureSpells" },
    },
    [13] = {
        passives = { "UnlockedSpellSlotLevel7" },
    },
    [15] = {
        passives = { "UnlockedSpellSlotLevel8" },
    },
    [17] = {
        passives = { "UnlockedSpellSlotLevel9" },
    },
    [18] = {
        passives = { "SpellMastery" },
        spells = { "Shout_SpellMastery" },
    },
    [20] = {
        passives = { "Wizard_SignatureSpells" },
    },
}

local WIZARD_SUBCLASS_EXPECTATIONS = {
    {
        passive = "Abjurer_14_SpellResistance",
        label = "AbjurationSchool",
    },
    {
        passive = "Diviner_14_GreaterPortent",
        label = "DivinationSchool",
        custom = function(character)
            grantExtraPortentDie(character)
            Log.Info("Wizard smoke invoked Greater Portent grant helper")
        end,
    },
    {
        passive = "Evoker_14_Overchannel",
        label = "EvocationSchool",
    },
    {
        passive = "Illusionist_14_IllusoryReality",
        label = "IllusionSchool",
    },
    {
        passive = "SongVictory",
        label = "Bladesinger",
    },
    {
        passive = "Conjurer_14_SplinteredSummons",
        label = "ConjurationSchool",
    },
    {
        passive = "SplitEnchantment",
        label = "EnchantmentSchool",
    },
    {
        passive = "Enchanter_14_AlterMemories",
        label = "EnchantmentSchool",
        spells = { "Shout_Apotheosis_ModifyMemory" },
    },
    {
        passive = "Necromancer_14_DeathsMaster",
        label = "NecromancySchool",
        spells = { "Shout_Apotheosis_BolsterUndead" },
    },
    {
        passive = "Transmuter_14_MasterTransmuter",
        label = "TransmutationSchool",
        spells = { "Target_Apotheosis_Panacea" },
    },
}

local function smokeAssertPresent(character, level, kind, value)
    if kind == "passive" then
        if smokeHasPassive(character, value) then
            Log.Info("Wizard PASS L" .. tostring(level) .. ": HasPassive(" .. value .. ")")
        else
            Log.Error("Wizard FAIL L" .. tostring(level) .. ": missing passive " .. value)
        end
    elseif kind == "spell" then
        if smokeHasSpell(character, value) then
            Log.Info("Wizard PASS L" .. tostring(level) .. ": HasSpell(" .. value .. ")")
        else
            Log.Error("Wizard FAIL L" .. tostring(level) .. ": missing spell " .. value)
        end
    end
end

local function smokeAssertAbsent(character, level, kind, value)
    if kind == "passive" then
        if smokeHasPassive(character, value) then
            Log.Error("Wizard FAIL L" .. tostring(level) .. ": unexpected passive " .. value)
        else
            Log.Info("Wizard PASS L" .. tostring(level) .. ": passive absent as expected (" .. value .. ")")
        end
    end
end

local function smokeRunWizardLevelChecks(character, level)
    local expectation = WIZARD_LEVEL_EXPECTATIONS[level]
    if not expectation then
        Log.Info("Wizard smoke L" .. tostring(level) .. ": no generic level assertion registered")
        return
    end

    if expectation.passives then
        for _, passive in ipairs(expectation.passives) do
            smokeAssertPresent(character, level, "passive", passive)
        end
    end

    if expectation.spells then
        for _, spell in ipairs(expectation.spells) do
            smokeAssertPresent(character, level, "spell", spell)
        end
    end

    if expectation.absentPassives then
        for _, passive in ipairs(expectation.absentPassives) do
            smokeAssertAbsent(character, level, "passive", passive)
        end
    end
end

local function smokeRunWizardSubclassChecks(character, level)
    if level < 14 then
        return
    end

    local matched = false
    for _, subclass in ipairs(WIZARD_SUBCLASS_EXPECTATIONS) do
        if smokeHasPassive(character, subclass.passive) then
            matched = true
            Log.Info("Wizard subclass smoke detected = " .. subclass.label)
            smokeAssertPresent(character, level, "passive", subclass.passive)
            if subclass.spells then
                for _, spell in ipairs(subclass.spells) do
                    smokeAssertPresent(character, level, "spell", spell)
                end
            end
            if subclass.custom then
                local ok, err = pcall(subclass.custom, character)
                if not ok then
                    Log.Error("Wizard FAIL L" .. tostring(level) .. ": subclass hook error for " .. subclass.passive .. ": " .. tostring(err))
                end
            end
        end
    end

    if not matched then
        Log.Warn("Wizard smoke L" .. tostring(level) .. ": no known level-14 wizard subclass passive detected")
    end
end

function Smoke.Wizard.RunSweep(startLevel, endLevel)
    local ok, err = pcall(function()
        if smokeState.running then
            error("Smoke run already in progress")
        end

        smokeState.running = true
        local host = smokeGetHost()
        local startAt = tonumber(startLevel) or Smoke.DEFAULT_START_LEVEL
        local endAt = tonumber(endLevel) or Smoke.DEFAULT_END_LEVEL

        Log.Info("Wizard smoke sweep starting: " .. tostring(startAt) .. " -> " .. tostring(endAt))
        smokeDescribeBuild(host)

        smokeRunTimedLevelSequence(host, startAt, endAt, function(level)
            Log.Info("Wizard smoke reached level " .. tostring(level))
            smokeRunWizardLevelChecks(host, level)
            smokeRunWizardSubclassChecks(host, level)
        end, function()
            Log.Info("Wizard smoke sweep complete")
            smokeState.running = false
        end)
    end)
    if not ok then
        smokeState.running = false
        Log.Error("Smoke.Wizard.RunSweep error: " .. tostring(err))
    end
end

-- =====================================================================
-- Manifest-driven validator: Apotheosis.Smoke.Wizard.RunManifest("SubclassName")
--
-- Policy (locked):
--   - One subclass per command invocation; run from a fresh game/load.
--   - STRICT: every expected passive must be present at the expected level.
--   - STOP ON FIRST FAILURE; do not continue and compound issues.
--   - Inferred manifests are fully allowed but flagged in console output;
--     inferred-manifest failures are still hard stops.
--   - Console-only output; no result files written at runtime.
--
-- Usage:
--   Apotheosis.Smoke.Wizard.RunManifest("EvocationSchool")
--   Apotheosis.Smoke.Wizard.RunManifest("BladesingingSchool")
-- =====================================================================

local WME = nil

-- Load expectations during bootstrap while mod context is known.
if Ext and type(Ext.Require) == "function" then
    local okWme, wmeOrErr = pcall(Ext.Require, "WizardManifestExpectations.lua")
    if okWme and type(wmeOrErr) == "table" then
        WME = wmeOrErr
        Log.Info("WizardManifestExpectations loaded at bootstrap")
    else
        Log.Warn("WizardManifestExpectations bootstrap load failed: " .. tostring(wmeOrErr))
    end
end

-- All-class expectations (generated by Scripts/build_all_class_expectations.py).
local CE = nil

if Ext and type(Ext.Require) == "function" then
    local okCe, ceOrErr = pcall(Ext.Require, "ClassExpectations.lua")
    if okCe and type(ceOrErr) == "table" then
        CE = ceOrErr
        Log.Info("ClassExpectations loaded at bootstrap")
    else
        Log.Warn("ClassExpectations bootstrap load failed: " .. tostring(ceOrErr))
    end

    local okFt, ftOrErr = pcall(Ext.Require, "FeatureTests.lua")
    if okFt and type(ftOrErr) == "table" then
        Log.Info("FeatureTests loaded at bootstrap")
    else
        Log.Warn("FeatureTests bootstrap load failed: " .. tostring(ftOrErr))
    end

    local okFr, frOrErr = pcall(Ext.Require, "FeatureRiders.lua")
    if okFr and type(frOrErr) == "table" then
        Log.Info("FeatureRiders loaded at bootstrap")
    else
        Log.Warn("FeatureRiders bootstrap load failed: " .. tostring(frOrErr))
    end

    local okEb, ebOrErr = pcall(Ext.Require, "EpicBoons.lua")
    if okEb and type(ebOrErr) == "table" then
        Log.Info("EpicBoons loaded at bootstrap")
    else
        Log.Warn("EpicBoons bootstrap load failed: " .. tostring(ebOrErr))
    end

    local okSm, smOrErr = pcall(Ext.Require, "SpellMastery.lua")
    if okSm and type(smOrErr) == "table" then
        Log.Info("SpellMastery loaded at bootstrap")
    else
        Log.Warn("SpellMastery bootstrap load failed: " .. tostring(smOrErr))
    end

    local okTs, tsOrErr = pcall(Ext.Require, "TimeStop.lua")
    if okTs and type(tsOrErr) == "table" then
        Log.Info("TimeStop loaded at bootstrap")
    else
        Log.Warn("TimeStop bootstrap load failed: " .. tostring(tsOrErr))
    end

    local okTp, tpOrErr = pcall(Ext.Require, "TruePolymorph.lua")
    if okTp and type(tpOrErr) == "table" then
        Log.Info("TruePolymorph loaded at bootstrap")
    else
        Log.Warn("TruePolymorph bootstrap load failed: " .. tostring(tpOrErr))
    end

    local okIm, imOrErr = pcall(Ext.Require, "IndomitableMight.lua")
    if okIm and type(imOrErr) == "table" then
        Log.Info("IndomitableMight loaded at bootstrap")
    else
        Log.Warn("IndomitableMight bootstrap load failed: " .. tostring(imOrErr))
    end

    pcall(Ext.Require, "MCMSettings.lua")
    local okXc, xcOrErr = pcall(Ext.Require, "XPCurve.lua")
    if okXc and type(xcOrErr) == "table" then
        Log.Info("XPCurve loaded at bootstrap")
    else
        Log.Warn("XPCurve bootstrap load failed: " .. tostring(xcOrErr))
    end

    local okGs, gsOrErr = pcall(Ext.Require, "Gunslinger.lua")
    if okGs and type(gsOrErr) == "table" then
        Log.Info("Gunslinger loaded at bootstrap")
    else
        Log.Warn("Gunslinger bootstrap load failed: " .. tostring(gsOrErr))
    end

    local okIl, ilOrErr = pcall(Ext.Require, "Illrigger.lua")
    if okIl and type(ilOrErr) == "table" then
        Log.Info("Illrigger loaded at bootstrap")
    else
        Log.Warn("Illrigger bootstrap load failed: " .. tostring(ilOrErr))
    end

    local okCf, cfOrErr = pcall(Ext.Require, "ClassFeatures.lua")
    if okCf and type(cfOrErr) == "table" then
        Log.Info("ClassFeatures loaded at bootstrap")
    else
        Log.Warn("ClassFeatures bootstrap load failed: " .. tostring(cfOrErr))
    end

    local okSf, sfOrErr = pcall(Ext.Require, "SubclassFeatures.lua")
    if okSf and type(sfOrErr) == "table" then
        Log.Info("SubclassFeatures loaded at bootstrap")
    else
        Log.Warn("SubclassFeatures bootstrap load failed: " .. tostring(sfOrErr))
    end

    local okPs, psOrErr = pcall(Ext.Require, "PrismaticSpray.lua")
    if okPs and type(psOrErr) == "table" then
        Log.Info("PrismaticSpray loaded at bootstrap")
    else
        Log.Warn("PrismaticSpray bootstrap load failed: " .. tostring(psOrErr))
    end

    local okSm, smnOrErr = pcall(Ext.Require, "Summons.lua")
    if okSm and type(smnOrErr) == "table" then
        Log.Info("Summons loaded at bootstrap")
    else
        Log.Warn("Summons bootstrap load failed: " .. tostring(smnOrErr))
    end

    local okSt, stOrErr = pcall(Ext.Require, "SpellTests.lua")
    if okSt and type(stOrErr) == "table" then
        Log.Info("SpellTests loaded at bootstrap")
    else
        Log.Warn("SpellTests bootstrap load failed: " .. tostring(stOrErr))
    end
end

-- Fallback execution path when SE console input is unreliable.
-- Set Enabled = true to auto-run a wizard manifest shortly after SessionLoaded.
local AUTO_SMOKE = {
    Enabled = false,
    Subclass = "EvocationSchool",
    DelayMs = 3000,
    MaxWaitTicks = 900, -- ~30s at 30hz
}

local autoSmokeState = {
    armed = false,
    started = false,
    tickCount = 0,
    tickHandler = nil,
}

local function autoSmokeUnsubscribeTick()
    if autoSmokeState.tickHandler then
        Ext.Events.Tick:Unsubscribe(autoSmokeState.tickHandler)
        autoSmokeState.tickHandler = nil
    end
end

local function autoSmokeStartWhenWorldReady()
    if not AUTO_SMOKE.Enabled or autoSmokeState.started then
        autoSmokeUnsubscribeTick()
        return
    end

    autoSmokeState.tickCount = autoSmokeState.tickCount + 1

    local host = getHostCharacterHandle()
    if host and host ~= "" and host ~= "00000000-0000-0000-0000-000000000000" then
        autoSmokeState.started = true
        autoSmokeUnsubscribeTick()

        Log.Warn(
            "AUTO_SMOKE world-ready host detected (" .. tostring(host) .. ") - running " ..
            tostring(AUTO_SMOKE.Subclass) .. " in " .. tostring(AUTO_SMOKE.DelayMs) .. "ms"
        )

        Ext.Timer.WaitFor(tonumber(AUTO_SMOKE.DelayMs) or 3000, function()
            local okAuto, errAuto = pcall(function()
                Smoke.Wizard.RunManifest(tostring(AUTO_SMOKE.Subclass))
            end)
            if not okAuto then
                Log.Error("AUTO_SMOKE trigger error: " .. tostring(errAuto))
            end
        end)
        return
    end

    local maxTicks = tonumber(AUTO_SMOKE.MaxWaitTicks) or 900
    if autoSmokeState.tickCount >= maxTicks then
        autoSmokeUnsubscribeTick()
        Log.Warn("AUTO_SMOKE timed out waiting for world-ready host; no auto-run triggered")
    end
end

local function smokeLoadWizardManifestExpectations()
    Log.Debug("RunManifest: resolving WizardManifestExpectations module")

    if type(WME) == "table" then
        Log.Debug("RunManifest: expectations already cached")
        return true
    end

    if type(_G.WizardManifestExpectations) == "table" then
        WME = _G.WizardManifestExpectations
        Log.Debug("RunManifest: loaded expectations from _G cache")
        return true
    end

    if type(require) == "function" then
        local okModule, moduleValue = pcall(require, "WizardManifestExpectations")
        if okModule and type(moduleValue) == "table" then
            WME = moduleValue
            Log.Debug("RunManifest: loaded expectations via require")
            return true
        end
        return false, "require('WizardManifestExpectations') failed: " .. tostring(moduleValue)
    end

    return false, "WizardManifestExpectations.lua could not be loaded (Ext.Require/require unavailable)"
end

--- Run the manifest-driven strict validator for a single wizard subclass.
--- @param subclassName  string   e.g. "EvocationSchool"
function Smoke.Wizard.RunManifest(subclassName)
    local ok, err = pcall(function()
        if smokeState.running then
            error("Smoke run already in progress - wait for it to complete or restart the game")
        end

        Log.Info("RunManifest requested for subclass = " .. tostring(subclassName))

        local loaded, loadErr = smokeLoadWizardManifestExpectations()
        if not loaded then
            error("Manifest expectations load failed: " .. tostring(loadErr))
        end

        -- ---- pre-flight: locate subclass data ----------------------------
        local subData = WME.subclasses[subclassName]
        if not subData then
            local available = {}
            for k in pairs(WME.subclasses) do
                available[#available + 1] = k
            end
            table.sort(available)
            error(
                "Unknown subclass '" .. tostring(subclassName) ..
                "'.  Available: " .. table.concat(available, ", ")
            )
        end

        -- ---- announce run ------------------------------------------------
        local kind = subData.manifest_kind or "unknown"
        if kind == "inferred" then
            Log.Warn("RunManifest: " .. subclassName .. " [INFERRED manifest - failures are hard stops]")
        else
            Log.Info("RunManifest: " .. subclassName .. " [canonical manifest]")
        end
        Log.Debug("RunManifest subclass guid = " .. tostring(subData.subclass_guid))

        local host = smokeGetHost()
        Log.Info("RunManifest host = " .. tostring(host))
        smokeDescribeBuild(host)

        smokeState.running = true

        -- ---- level sequence 13 -> 20, strict stop-on-first-failure ------
        local failed = false
        local failInfo = nil

        local function checkPassive(level, passive, kind_label)
            if failed then return end
            if smokeHasPassive(host, passive) then
                Log.Info("  PASS L" .. level .. " [" .. kind_label .. "] HasPassive(" .. passive .. ")")
            else
                failed  = true
                failInfo = "L" .. level .. " [" .. kind_label .. "] missing passive: " .. passive
                Log.Error("  FAIL " .. failInfo)
                Log.Error("  STOPPING: fix '" .. passive .. "' before continuing")
            end
        end

        local function validateLevel(level)
            if failed then return end

            local entry = subData.levels[level]
            if not entry then
                Log.Warn("  RunManifest L" .. level .. ": no entry in expectation table - skipping")
                return
            end

            Log.Debug(
                "  RunManifest L" .. level .. ": base=" .. tostring(#(entry.base_passives or {})) ..
                ", subclass=" .. tostring(#(entry.subclass_passives or {}))
            )

            -- base wizard grants
            for _, passive in ipairs(entry.base_passives or {}) do
                checkPassive(level, passive, "wizard-base")
                if failed then return end
            end

            -- subclass grants
            for _, passive in ipairs(entry.subclass_passives or {}) do
                checkPassive(level, passive, subclassName)
                if failed then return end
            end
        end

        local function step(level)
            if level > 20 or failed then
                -- ---- final summary --------------------------------------
                if failed then
                    Log.Error("RunManifest " .. subclassName .. ": FAILED at " .. (failInfo or "?"))
                else
                    Log.Info("RunManifest " .. subclassName .. ": ALL CHECKS PASSED (L13-L20)")
                end
                smokeState.running = false
                return
            end

            Log.Info("RunManifest: setting level " .. level)
            smokeSetLevel(host, level)

            Ext.Timer.WaitFor(Smoke.LEVEL_SETTLE_MS, function()
                smokeRestore(host)
                Ext.Timer.WaitFor(Smoke.POST_RESTORE_SETTLE_MS, function()
                    local effectiveLevel = smokeGetLevel(host)
                    if effectiveLevel and effectiveLevel < level then
                        failed = true
                        failInfo =
                            "L" .. level ..
                            " [preflight] engine level remained " .. tostring(effectiveLevel) ..
                            " after SetLevel(" .. tostring(level) .. ")"
                        Log.Error("  FAIL " .. failInfo)
                        Log.Error("  STOPPING: host has unresolved level-up choices; complete level-up UI flow first, then retry")
                        step(level + 1)
                        return
                    end

                    Log.Info("RunManifest: checking level " .. level)
                    validateLevel(level)
                    step(level + 1)
                end)
            end)
        end

        step(13)
    end)

    if not ok then
        smokeState.running = false
        Log.Error("RunManifest error: " .. tostring(err))
    end
end

local function smokeTryAddExperience(character, amount)
    if Osi.AddExperience then
        local ok, err = pcall(Osi.AddExperience, character, amount)
        if ok then
            return true, "AddExperience"
        end
        Log.Warn("smokeTryAddExperience: AddExperience failed: " .. tostring(err))
    end

    if Osi.AddExplorationExperience then
        local ok, err = pcall(Osi.AddExplorationExperience, character, amount)
        if ok then
            return true, "AddExplorationExperience"
        end
        Log.Warn("smokeTryAddExperience: AddExplorationExperience failed: " .. tostring(err))
    end

    return false, "No usable XP API (AddExperience/AddExplorationExperience unavailable or failing)"
end

-- XP needed to advance from N -> N+1, mirroring the mod's XPData.txt.
local XP_TO_NEXT_LEVEL = {
    [1] = 300,
    [2] = 600,
    [3] = 1800,
    [4] = 3800,
    [5] = 6500,
    [6] = 8000,
    [7] = 9000,
    [8] = 9000,
    [9] = 9500,
    [10] = 10000,
    [11] = 10500,
    [12] = 10500,
    [13] = 11000,
    [14] = 11000,
    [15] = 11500,
    [16] = 11500,
    [17] = 12000,
    [18] = 12000,
    [19] = 11500,
}

local function smokeGetXpToNextLevel(level)
    return XP_TO_NEXT_LEVEL[tonumber(level)]
end

local function smokeGetWizardSpellbookCounts(character)
    if not Ext or not Ext.Entity or type(Ext.Entity.Get) ~= "function" then
        return nil, "Ext.Entity.Get unavailable"
    end

    local entity = Ext.Entity.Get(character)
    if not entity or not entity.SpellBook or not entity.SpellBook.Spells then
        return nil, "SpellBook component unavailable"
    end

    local known = 0
    local prepared = 0
    local foundPreparedFlag = false

    local function isPreparedEntry(spell)
        local v = spell.IsPrepared
        if v == nil then v = spell.Prepared end
        if v == nil then v = spell.IsMemorized end
        if v == nil then v = spell.Memorized end
        if v == nil then v = spell.IsSelected end
        if v == nil then return nil end
        return v == true or v == 1
    end

    for _, spell in ipairs(entity.SpellBook.Spells) do
        known = known + 1
        local prep = isPreparedEntry(spell)
        if prep ~= nil then
            foundPreparedFlag = true
            if prep then
                prepared = prepared + 1
            end
        end
    end

    if not foundPreparedFlag then
        return nil, "Prepared flag not discoverable on SpellBook entries"
    end

    return {
        known = known,
        prepared = prepared,
    }
end

local function smokeGetIntModifier(character)
    if not Ext or not Ext.Entity or type(Ext.Entity.Get) ~= "function" then
        return nil
    end

    local entity = Ext.Entity.Get(character)
    if not entity or not entity.Stats or not entity.Stats.Abilities then
        return nil
    end

    -- Abilities array is 1-indexed with [1]=None; Intelligence sits at index 5.
    local intelligence = tonumber(entity.Stats.Abilities[5])
    if not intelligence then
        return nil
    end

    return math.floor((intelligence - 10) / 2)
end

--- Interactive manual-level flow:
--- 1) Start once for a subclass.
--- 2) Validate current committed level when in check range.
--- 3) Grant EXACT XP for current->next level.
--- 4) Wait for player to complete choices until next level is committed.
--- 5) Repeat until L20 or first failure.
function Smoke.Wizard.RunManifestInteractive(subclassName, startLevel)
    local ok, err = pcall(function()
        if smokeState.running then
            error("Smoke run already in progress - wait for it to complete or restart the game")
        end

        Log.Info("RunManifestInteractive requested for subclass = " .. tostring(subclassName))

        local loaded, loadErr = smokeLoadWizardManifestExpectations()
        if not loaded then
            error("Manifest expectations load failed: " .. tostring(loadErr))
        end

        local subData = WME.subclasses[subclassName]
        if not subData then
            local available = {}
            for k in pairs(WME.subclasses) do
                available[#available + 1] = k
            end
            table.sort(available)
            error(
                "Unknown subclass '" .. tostring(subclassName) ..
                "'.  Available: " .. table.concat(available, ", ")
            )
        end

        local host = smokeGetHost()
        Log.Info("RunManifestInteractive host = " .. tostring(host))
        smokeDescribeBuild(host)

        local checkStart = tonumber(startLevel) or 13
        if checkStart < 1 then checkStart = 1 end
        if checkStart > 20 then checkStart = 20 end

        smokeState.running = true

        local failed = false
        local failInfo = nil

        local function finish()
            if failed then
                Log.Error("RunManifestInteractive " .. tostring(subclassName) .. ": FAILED at " .. tostring(failInfo))
            else
                Log.Info("RunManifestInteractive " .. tostring(subclassName) .. ": ALL CHECKS PASSED (L" .. tostring(checkStart) .. "-L20)")
            end
            smokeState.running = false
        end

        local function checkPassive(level, passive, kindLabel)
            if failed then return end
            if smokeHasPassive(host, passive) then
                Log.Info("  PASS L" .. tostring(level) .. " [" .. kindLabel .. "] HasPassive(" .. passive .. ")")
            else
                failed = true
                failInfo = "L" .. tostring(level) .. " [" .. kindLabel .. "] missing passive: " .. passive
                Log.Error("  FAIL " .. tostring(failInfo))
                Log.Error("  STOPPING: fix '" .. tostring(passive) .. "' before continuing")
            end
        end

        local function validateLevel(level)
            if failed then return end

            if level < checkStart then
                Log.Debug("  RunManifestInteractive L" .. tostring(level) .. ": below checkStart L" .. tostring(checkStart) .. " - skipping checks")
                return
            end

            local entry = subData.levels[level]
            if not entry then
                Log.Warn("  RunManifestInteractive L" .. tostring(level) .. ": no entry in expectation table - skipping")
                return
            end

            Log.Debug(
                "  RunManifestInteractive L" .. tostring(level) .. ": base=" .. tostring(#(entry.base_passives or {})) ..
                ", subclass=" .. tostring(#(entry.subclass_passives or {}))
            )

            for _, passive in ipairs(entry.base_passives or {}) do
                checkPassive(level, passive, "wizard-base")
                if failed then return end
            end

            for _, passive in ipairs(entry.subclass_passives or {}) do
                checkPassive(level, passive, tostring(subclassName))
                if failed then return end
            end

            if level >= 13 then
                local counts, countErr = smokeGetWizardSpellbookCounts(host)
                if not counts then
                    failed = true
                    failInfo = "L" .. tostring(level) .. " [wizard-spellbook] " .. tostring(countErr)
                    Log.Error("  FAIL " .. tostring(failInfo))
                    Log.Error("  STOPPING: cannot validate wizard spellbook/prepared counts")
                    return
                end

                local expectedKnownMin = 6 + math.max(0, ((tonumber(level) or 1) - 1) * 2)
                if counts.known < expectedKnownMin then
                    failed = true
                    failInfo =
                        "L" .. tostring(level) ..
                        " [wizard-spellbook] known spells " .. tostring(counts.known) ..
                        " < expected minimum " .. tostring(expectedKnownMin)
                    Log.Error("  FAIL " .. tostring(failInfo))
                    Log.Error("  STOPPING: wizard did not gain enough known spells by level-up progression")
                    return
                end

                local intMod = smokeGetIntModifier(host)
                if intMod ~= nil then
                    local expectedPreparedMin = math.max(1, (tonumber(level) or 1) + intMod)
                    if counts.prepared < expectedPreparedMin then
                        failed = true
                        failInfo =
                            "L" .. tostring(level) ..
                            " [wizard-prepared] prepared spells " .. tostring(counts.prepared) ..
                            " < expected minimum " .. tostring(expectedPreparedMin)
                        Log.Error("  FAIL " .. tostring(failInfo))
                        Log.Error("  STOPPING: wizard prepared spell count below expected level+INT threshold")
                        return
                    end

                    Log.Info(
                        "  PASS L" .. tostring(level) ..
                        " [wizard-spellbook] known=" .. tostring(counts.known) ..
                        ", prepared=" .. tostring(counts.prepared) ..
                        ", expectedPreparedMin=" .. tostring(expectedPreparedMin)
                    )
                else
                    Log.Warn("  RunManifestInteractive L" .. tostring(level) .. ": could not resolve INT modifier; prepared minimum not enforced")
                end
            end
        end

        local driveNextStep

        local function waitForCommittedLevel(targetLevel, startedAtMs)
            if failed then
                finish()
                return
            end

            local current = smokeGetLevel(host)
            if current and current >= targetLevel then
                Log.Info("RunManifestInteractive: level " .. tostring(targetLevel) .. " committed (current=" .. tostring(current) .. ")")
                smokeRestore(host)
                Ext.Timer.WaitFor(Smoke.POST_RESTORE_SETTLE_MS, function()
                    validateLevel(targetLevel)
                    if failed or targetLevel >= 20 then
                        finish()
                        return
                    end
                    Ext.Timer.WaitFor(300, driveNextStep)
                end)
                return
            end

            if startedAtMs >= Smoke.INTERACTIVE_LEVEL_TIMEOUT_MS then
                failed = true
                failInfo =
                    "L" .. tostring(targetLevel) ..
                    " [interactive-timeout] waiting for committed level-up choices (current=" .. tostring(current) .. ")"
                Log.Error("  FAIL " .. tostring(failInfo))
                Log.Error("  STOPPING: complete level-up choices in UI, then rerun interactive smoke")
                finish()
                return
            end

            Ext.Timer.WaitFor(Smoke.INTERACTIVE_POLL_MS, function()
                waitForCommittedLevel(targetLevel, startedAtMs + Smoke.INTERACTIVE_POLL_MS)
            end)
        end

        driveNextStep = function()
            if failed then
                finish()
                return
            end

            local current = smokeGetLevel(host)
            if not current then
                failed = true
                failInfo = "[interactive] unable to resolve current committed level"
                Log.Error("  FAIL " .. tostring(failInfo))
                finish()
                return
            end

            if current > 20 then
                current = 20
            end

            Log.Info("RunManifestInteractive: committed current level = " .. tostring(current))
            validateLevel(current)
            if failed then
                finish()
                return
            end

            if current >= 20 then
                finish()
                return
            end

            local xpDelta = smokeGetXpToNextLevel(current)
            if not xpDelta then
                failed = true
                failInfo = "[interactive] missing XP delta for level " .. tostring(current)
                Log.Error("  FAIL " .. tostring(failInfo))
                finish()
                return
            end

            local targetLevel = current + 1
            local okXp, xpSourceOrErr = smokeTryAddExperience(host, xpDelta)
            if okXp then
                Log.Info(
                    "RunManifestInteractive: granted XP delta " .. tostring(xpDelta) ..
                    " for L" .. tostring(current) .. " -> L" .. tostring(targetLevel) ..
                    " via " .. tostring(xpSourceOrErr)
                )
            else
                failed = true
                failInfo = "L" .. tostring(targetLevel) .. " [interactive-xp] " .. tostring(xpSourceOrErr)
                Log.Error("  FAIL " .. tostring(failInfo))
                finish()
                return
            end

            Log.Info("RunManifestInteractive: waiting for level-up choices to commit L" .. tostring(targetLevel))
            waitForCommittedLevel(targetLevel, 0)
        end

        Log.Info(
            "RunManifestInteractive: begin interactive chain from current level -> L20; " ..
            "checks start at L" .. tostring(checkStart) .. ""
        )

        driveNextStep()
    end)

    if not ok then
        smokeState.running = false
        Log.Error("RunManifestInteractive error: " .. tostring(err))
    end
end

--- Validate one manifest level only (current host level by default).
--- @param subclassName string
--- @param levelOverride number|nil
function Smoke.Wizard.CheckLevel(subclassName, levelOverride)
    local ok, err = pcall(function()
        if smokeState.running then
            error("Smoke run already in progress - wait for it to complete or restart the game")
        end

        local loaded, loadErr = smokeLoadWizardManifestExpectations()
        if not loaded then
            error("Manifest expectations load failed: " .. tostring(loadErr))
        end

        local subData = WME.subclasses[subclassName]
        if not subData then
            local available = {}
            for k in pairs(WME.subclasses) do
                available[#available + 1] = k
            end
            table.sort(available)
            error(
                "Unknown subclass '" .. tostring(subclassName) ..
                "'.  Available: " .. table.concat(available, ", ")
            )
        end

        local host = smokeGetHost()
        local level = tonumber(levelOverride) or smokeGetLevel(host)
        if not level then
            error("Unable to resolve host level for single-level manifest check")
        end

        if level < 13 or level > 20 then
            error("Single-level manifest check requires level 13-20; current/requested = " .. tostring(level))
        end

        local entry = subData.levels[level]
        if not entry then
            error("No manifest entry found for subclass " .. tostring(subclassName) .. " at level " .. tostring(level))
        end

        Log.Info("RunManifestCheck: " .. tostring(subclassName) .. " at L" .. tostring(level))

        local failed = false
        local failInfo = nil

        local function checkPassive(passive, kindLabel)
            if failed then return end
            if smokeHasPassive(host, passive) then
                Log.Info("  PASS L" .. tostring(level) .. " [" .. kindLabel .. "] HasPassive(" .. passive .. ")")
            else
                failed = true
                failInfo = "L" .. tostring(level) .. " [" .. kindLabel .. "] missing passive: " .. passive
                Log.Error("  FAIL " .. failInfo)
            end
        end

        for _, passive in ipairs(entry.base_passives or {}) do
            checkPassive(passive, "wizard-base")
        end

        for _, passive in ipairs(entry.subclass_passives or {}) do
            checkPassive(passive, tostring(subclassName))
        end

        if failed then
            Log.Error("RunManifestCheck " .. tostring(subclassName) .. ": FAILED at " .. tostring(failInfo))
        else
            Log.Info("RunManifestCheck " .. tostring(subclassName) .. ": PASS at L" .. tostring(level))
        end
    end)

    if not ok then
        Log.Error("RunManifestCheck error: " .. tostring(err))
    end
end

--- Probe whether RequestAutoLevel can resolve pending level-up state for the host.
function Smoke.Wizard.TryAutoLevel()
    local ok, err = pcall(function()
        local host = smokeGetHost()
        local before = smokeGetLevel(host)
        Log.Info("TryAutoLevel host=" .. tostring(host) .. " level(before)=" .. tostring(before))

        if not Osi.RequestAutoLevel then
            Log.Error("TryAutoLevel: Osi.RequestAutoLevel is unavailable in this runtime")
            return
        end

        Osi.RequestAutoLevel(host)

        -- Let level-up side effects settle before checking committed level.
        Ext.Timer.WaitFor(800, function()
            local after = smokeGetLevel(host)
            if after and before and after > before then
                Log.Info("TryAutoLevel: SUCCESS level(after)=" .. tostring(after))
            else
                Log.Warn(
                    "TryAutoLevel: no committed level change detected (before=" ..
                    tostring(before) .. ", after=" .. tostring(after) .. ")"
                )
            end
        end)
    end)

    if not ok then
        Log.Error("TryAutoLevel error: " .. tostring(err))
    end
end

-- =====================================================================
-- Generic validator: covers EVERY class and subclass in
-- ClassExpectations.lua.  Subclass checks automatically include the
-- parent class's base grants for the same level.
--
-- Usage:
--   !aposub EvocationSchool 14      -- check one level
--   !aposubsweep ZealotPath         -- sweep 13-20, stop-on-first-failure
--   !apolist                        -- list every known class/subclass
-- =====================================================================

Smoke.Any = Smoke.Any or {}

local function smokeLoadClassExpectations()
    if type(CE) == "table" then
        return true
    end
    if type(_G.ApotheosisClassExpectations) == "table" then
        CE = _G.ApotheosisClassExpectations
        return true
    end
    if type(require) == "function" then
        local okModule, moduleValue = pcall(require, "ClassExpectations")
        if okModule and type(moduleValue) == "table" then
            CE = moduleValue
            return true
        end
        return false, "require('ClassExpectations') failed: " .. tostring(moduleValue)
    end
    return false, "ClassExpectations.lua could not be loaded (Ext.Require/require unavailable)"
end

--- Merge subclass + parent-class expected passives into checks[level] lists.
local function smokeResolveExpectations(name)
    local checks = {}

    local function addLevels(levels, kind)
        for lvl, entry in pairs(levels or {}) do
            checks[lvl] = checks[lvl] or {}
            for _, passive in ipairs(entry.passives or {}) do
                checks[lvl][#checks[lvl] + 1] = { passive = passive, kind = kind }
            end
        end
    end

    local sub = CE.subclasses[name]
    if sub then
        addLevels(sub.levels, name)
        local parent = sub.parent and CE.classes[sub.parent]
        if parent then
            addLevels(parent.levels, tostring(sub.parent) .. "-base")
        end
        return { label = name, parent = sub.parent, checks = checks }
    end

    local cls = CE.classes[name]
    if cls then
        addLevels(cls.levels, tostring(name) .. "-base")
        return { label = name, parent = nil, checks = checks }
    end

    return nil
end

local function smokeListAvailable()
    local classes, subs = {}, {}
    for k in pairs(CE.classes) do classes[#classes + 1] = k end
    for k in pairs(CE.subclasses) do subs[#subs + 1] = k end
    table.sort(classes)
    table.sort(subs)
    return classes, subs
end

--- Check one level's expected passives; returns ok, firstFailureDescription.
local function smokeCheckLevelAgainst(resolved, host, level)
    local entries = resolved.checks[level]
    if not entries or #entries == 0 then
        Log.Info("  INFO L" .. tostring(level) .. ": no expected passive grants at this level")
        return true, nil
    end
    for _, check in ipairs(entries) do
        if smokeHasPassive(host, check.passive) then
            Log.Info("  PASS L" .. tostring(level) .. " [" .. check.kind .. "] HasPassive(" .. check.passive .. ")")
        else
            local info = "L" .. tostring(level) .. " [" .. check.kind .. "] missing passive: " .. check.passive
            Log.Error("  FAIL " .. info)
            return false, info
        end
    end
    return true, nil
end

--- Validate the host at a single level (current host level by default).
function Smoke.Any.CheckLevel(name, levelOverride)
    local ok, err = pcall(function()
        local loaded, loadErr = smokeLoadClassExpectations()
        if not loaded then
            error("ClassExpectations load failed: " .. tostring(loadErr))
        end

        local resolved = smokeResolveExpectations(tostring(name))
        if not resolved then
            local classes, subs = smokeListAvailable()
            error(
                "Unknown class/subclass '" .. tostring(name) .. "'. " ..
                tostring(#classes) .. " classes / " .. tostring(#subs) ..
                " subclasses available - run !apolist"
            )
        end

        local host = smokeGetHost()
        local level = tonumber(levelOverride) or smokeGetLevel(host)
        if not level then
            error("Unable to resolve host level for subclass check")
        end

        Log.Info(
            "SubclassCheck: " .. resolved.label .. " at L" .. tostring(level) ..
            (resolved.parent and (" (parent " .. resolved.parent .. ")") or "")
        )

        local passOk, failInfo = smokeCheckLevelAgainst(resolved, host, level)
        if passOk then
            Log.Info("SubclassCheck " .. resolved.label .. ": PASS at L" .. tostring(level))
        else
            Log.Error("SubclassCheck " .. resolved.label .. ": FAILED at " .. tostring(failInfo))
        end
    end)
    if not ok then
        Log.Error("SubclassCheck error: " .. tostring(err))
    end
end

--- Sweep the host through levels (default 13-20) validating each level.
function Smoke.Any.RunSweep(name, startLevel, endLevel)
    local ok, err = pcall(function()
        if smokeState.running then
            error("Smoke run already in progress - wait for it to complete or restart the game")
        end

        local loaded, loadErr = smokeLoadClassExpectations()
        if not loaded then
            error("ClassExpectations load failed: " .. tostring(loadErr))
        end

        local resolved = smokeResolveExpectations(tostring(name))
        if not resolved then
            error("Unknown class/subclass '" .. tostring(name) .. "' - run !apolist for the full list")
        end

        local startAt = tonumber(startLevel) or Smoke.DEFAULT_START_LEVEL
        local endAt = tonumber(endLevel) or Smoke.DEFAULT_END_LEVEL
        local host = smokeGetHost()

        Log.Info("SubclassSweep " .. resolved.label .. ": L" .. tostring(startAt) .. " -> L" .. tostring(endAt))
        smokeDescribeBuild(host)

        smokeState.running = true
        local failed = false
        local failInfo = nil

        smokeRunTimedLevelSequence(host, startAt, endAt, function(level)
            if failed then return end
            local passOk, info = smokeCheckLevelAgainst(resolved, host, level)
            if not passOk then
                failed = true
                failInfo = info
            end
        end, function()
            smokeState.running = false
            if failed then
                Log.Error("SubclassSweep " .. resolved.label .. ": FAILED at " .. tostring(failInfo))
            else
                Log.Info("SubclassSweep " .. resolved.label .. ": ALL CHECKS PASSED")
            end
        end)
    end)
    if not ok then
        smokeState.running = false
        Log.Error("SubclassSweep error: " .. tostring(err))
    end
end

local function smokeConsoleSubCheck(cmd, name, level)
    if not name or tostring(name) == "" then
        Log.Error("Console command usage: !aposub <ClassOrSubclassName> [Level]")
        Log.Error("Example: !aposub ZealotPath 14   (run !apolist for all names)")
        return
    end
    Log.Info("Console command !" .. tostring(cmd) .. " " .. tostring(name) .. " " .. tostring(level or ""))
    Smoke.Any.CheckLevel(tostring(name), tonumber(level))
end

local function smokeConsoleSubSweep(cmd, name, startLevel, endLevel)
    if not name or tostring(name) == "" then
        Log.Error("Console command usage: !aposubsweep <ClassOrSubclassName> [start] [end]")
        Log.Error("Example: !aposubsweep EvocationSchool 13 20")
        return
    end
    Log.Info("Console command !" .. tostring(cmd) .. " " .. tostring(name))
    Smoke.Any.RunSweep(tostring(name), startLevel, endLevel)
end

local function smokeConsoleList(cmd)
    Log.Info("Console command !" .. tostring(cmd))
    local loaded, loadErr = smokeLoadClassExpectations()
    if not loaded then
        Log.Error("ClassExpectations load failed: " .. tostring(loadErr))
        return
    end
    local classes, subs = smokeListAvailable()
    Log.Info("Classes (" .. tostring(#classes) .. "): " .. table.concat(classes, ", "))
    Log.Info("Subclasses (" .. tostring(#subs) .. "): " .. table.concat(subs, ", "))
end

-- =====================================================================
-- Level-up WATCH MODE.
--
-- While enabled, every LeveledUp event on a party member is resolved to
-- its class/subclass (via the UUID maps in ClassExpectations.lua). If
-- the new level has expected grants - including sub-13 levels where
-- Apotheosis moved features back to their PHB 2024 positions - the
-- expectation checks run automatically, followed by any registered
-- functional feature tests for the passives granted at that level.
--
-- Flow: enable once (!apowatch on), then level up in-game with real
-- UI choices; PASS/FAIL streams to the SE console/log per level.
-- =====================================================================

local watchState = { enabled = false }

--- Resolve a live character's class/subclass to expectation-table names.
local function watchResolveClass(character)
    local okResolve, result = pcall(function()
        if not Ext.Entity or type(Ext.Entity.Get) ~= "function" then return nil end
        local entity = Ext.Entity.Get(character)
        if not entity or not entity.Classes or not entity.Classes.Classes then return nil end
        local best = nil
        for _, c in ipairs(entity.Classes.Classes) do
            local cls = CE and CE.classes and CE.class_uuids[tostring(c.ClassUUID)] or nil
            local sub = CE and CE.subclasses and CE.subclass_uuids[tostring(c.SubClassUUID)] or nil
            if cls or sub then
                best = { class = cls, subclass = sub }
                if sub then break end
            end
        end
        return best
    end)
    if okResolve then return result end
    Log.Debug("Watch: class resolution error: " .. tostring(result))
    return nil
end

local function watchOnLeveledUp(character)
    if not watchState.enabled then return end
    -- a running sweep already validates each level; don't double-fire
    if smokeState.running then return end
    local ok, err = pcall(function()
        local loaded, loadErr = smokeLoadClassExpectations()
        if not loaded then
            Log.Warn("Watch: ClassExpectations unavailable: " .. tostring(loadErr))
            return
        end

        local level = smokeGetLevel(character)
        if not level then return end

        local info = watchResolveClass(character)
        local name = info and (info.subclass or info.class)
        if not name then
            Log.Debug("Watch: no expectation mapping for " .. tostring(character))
            return
        end

        local resolved = smokeResolveExpectations(name)
        if not resolved then return end

        local entries = resolved.checks[level]
        if not entries or #entries == 0 then
            Log.Info("Watch: " .. name .. " reached L" .. tostring(level) .. " (no expected grants - skipping)")
            return
        end

        Log.Info("Watch: " .. name .. " reached L" .. tostring(level) .. " - validating in " ..
            tostring(Smoke.POST_RESTORE_SETTLE_MS) .. "ms")

        Ext.Timer.WaitFor(Smoke.POST_RESTORE_SETTLE_MS, function()
            local okCheck, errCheck = pcall(function()
                local passOk, failInfo = smokeCheckLevelAgainst(resolved, character, level)
                if passOk then
                    Log.Info("Watch " .. name .. " L" .. tostring(level) .. ": ALL CHECKS PASSED")
                else
                    Log.Error("Watch " .. name .. " L" .. tostring(level) .. ": FAILED at " .. tostring(failInfo))
                end

                local ft = _G.ApotheosisFeatureTests
                if ft then
                    local granted = {}
                    for _, check in ipairs(entries) do
                        granted[#granted + 1] = check.passive
                    end
                    ft.RunForPassives(character, granted)
                end
            end)
            if not okCheck then
                Log.Error("Watch validation error: " .. tostring(errCheck))
            end
        end)
    end)
    if not ok then
        Log.Error("Watch LeveledUp handler error: " .. tostring(err))
    end
end

if Ext.Osiris and type(Ext.Osiris.RegisterListener) == "function" then
    Ext.Osiris.RegisterListener("LeveledUp", 1, "after", watchOnLeveledUp)
end

local function smokeConsoleWatch(cmd, arg)
    local mode = tostring(arg or ""):lower()
    if mode == "on" then
        watchState.enabled = true
        Log.Info("Watch mode ENABLED - level up in-game; checks run automatically at levels with expected grants")
    elseif mode == "off" then
        watchState.enabled = false
        Log.Info("Watch mode disabled")
    else
        Log.Info("Watch mode is " .. (watchState.enabled and "ON" or "OFF") .. ". Usage: !apowatch on|off")
    end
end

local function smokeConsoleFeature(cmd, passive, target)
    if not passive or tostring(passive) == "" then
        Log.Error("Console command usage: !apofeature <PassiveName> [TargetGuid]")
        Log.Error("Run !apofeatures for the registered test list")
        return
    end
    local ft = _G.ApotheosisFeatureTests
    if not ft then
        Log.Error("FeatureTests module not loaded")
        return
    end
    Log.Info("Console command !" .. tostring(cmd) .. " " .. tostring(passive))
    ft.Run(tostring(passive), target and tostring(target) or nil)
end

local function smokeConsoleFeatureList(cmd)
    local ft = _G.ApotheosisFeatureTests
    if not ft then
        Log.Error("FeatureTests module not loaded")
        return
    end
    ft.List()
end

local function smokeConsoleSpellList(cmd)
    local st = _G.ApotheosisSpellTests
    if not st then
        Log.Error("SpellTests module not loaded")
        return
    end
    st.List()
end

local function smokeConsoleSpells(cmd, subclass)
    local st = _G.ApotheosisSpellTests
    if not st then
        Log.Error("SpellTests module not loaded")
        return
    end
    if not subclass or tostring(subclass) == "" then
        Log.Error("Console command usage: !apospells <Subclass>")
        Log.Error("Run !apospelllist for every subclass with assigned spell tests")
        return
    end
    Log.Info("Console command !" .. tostring(cmd) .. " " .. tostring(subclass))
    st.RunForSubclass(tostring(subclass))
end

local function smokeConsoleSpell(cmd, spellId)
    local st = _G.ApotheosisSpellTests
    if not st then
        Log.Error("SpellTests module not loaded")
        return
    end
    if not spellId or tostring(spellId) == "" then
        Log.Error("Console command usage: !apospell <SpellStatId>")
        Log.Error("Run !apospelllist for every spell id")
        return
    end
    Log.Info("Console command !" .. tostring(cmd) .. " " .. tostring(spellId))
    st.RunOne(tostring(spellId))
end

local function smokeConsoleSpawn(cmd, templateKey, factionKey)
    local ft = _G.ApotheosisFeatureTests
    if not ft then
        Log.Error("FeatureTests module not loaded")
        return
    end
    if not templateKey or tostring(templateKey) == "" then
        local names = {}
        for k in pairs(ft.Config.Templates) do names[#names + 1] = k end
        table.sort(names)
        Log.Error("Console command usage: !apospawn <template> [faction]")
        Log.Error("Templates: " .. table.concat(names, ", ") .. "  Factions: hostile, friendly, neutral")
        return
    end
    local okSpawn, errSpawn = pcall(function()
        local host = ft.GetHost()
        ft.SpawnCreature(host, tostring(templateKey), tostring(factionKey or "hostile"), 3, 3, function(guid, why)
            if guid then
                Log.Info("Spawned " .. tostring(templateKey) .. " (" .. tostring(factionKey or "hostile") .. "): " .. tostring(guid))
                Log.Info("Clean up with: Osi.RequestDelete(\"" .. tostring(guid) .. "\")")
            else
                Log.Error("Spawn failed: " .. tostring(why))
            end
        end)
    end)
    if not okSpawn then
        Log.Error("Spawn error: " .. tostring(errSpawn))
    end
end

local function smokeConsoleRunManifest(cmd, subclassName)
    if not subclassName or tostring(subclassName) == "" then
        Log.Error("Console command usage: !apowizmanifest <SubclassName>")
        Log.Error("Available subclasses: AbjurationSchool, BladesingingSchool, DivinationSchool, EvocationSchool, IllusionSchool")
        return
    end

    Log.Info("Console command !" .. tostring(cmd) .. " " .. tostring(subclassName))
    Smoke.Wizard.RunManifest(tostring(subclassName))
end

local function smokeConsoleRunManifestInteractive(cmd, subclassName, startLevel)
    if not subclassName or tostring(subclassName) == "" then
        Log.Error("Console command usage: !apowizinteractive <SubclassName>")
        Log.Error("Example: !apowizinteractive EvocationSchool")
        return
    end

    if startLevel ~= nil and tostring(startLevel) ~= "" then
        Log.Warn("Console command !" .. tostring(cmd) .. ": ignoring legacy StartLevel argument; command is now subclass-only")
    end

    Log.Info("Console command !" .. tostring(cmd) .. " " .. tostring(subclassName))
    Smoke.Wizard.RunManifestInteractive(tostring(subclassName))
end

local function smokeConsoleRunManifestCheck(cmd, subclassName, level)
    if not subclassName or tostring(subclassName) == "" then
        Log.Error("Console command usage: !apowizcheck <SubclassName> [Level]")
        Log.Error("Example: !apowizcheck EvocationSchool 13")
        return
    end

    Log.Info("Console command !" .. tostring(cmd) .. " " .. tostring(subclassName) .. " " .. tostring(level or ""))
    Smoke.Wizard.CheckLevel(tostring(subclassName), tonumber(level))
end

local function smokeConsoleTryAutoLevel(cmd)
    Log.Info("Console command !" .. tostring(cmd))
    Smoke.Wizard.TryAutoLevel()
end

local function smokeConsoleRunSweep(cmd, startLevel, endLevel)
    Log.Info(
        "Console command !" .. tostring(cmd) ..
        " start=" .. tostring(startLevel or Smoke.DEFAULT_START_LEVEL) ..
        " end=" .. tostring(endLevel or Smoke.DEFAULT_END_LEVEL)
    )
    Smoke.Wizard.RunSweep(startLevel, endLevel)
end

local function smokeConsoleHelp(cmd)
    Log.Info("Console command !" .. tostring(cmd))
    Smoke.Help()
    Smoke.Wizard.Help()
end

if Ext and type(Ext.RegisterConsoleCommand) == "function" then
    Ext.RegisterConsoleCommand("aposmokehelp", smokeConsoleHelp)
    Ext.RegisterConsoleCommand("apowizmanifest", smokeConsoleRunManifest)
    Ext.RegisterConsoleCommand("apowizinteractive", smokeConsoleRunManifestInteractive)
    Ext.RegisterConsoleCommand("apowizcheck", smokeConsoleRunManifestCheck)
    Ext.RegisterConsoleCommand("apowizautolevel", smokeConsoleTryAutoLevel)
    Ext.RegisterConsoleCommand("apowizsweep", smokeConsoleRunSweep)
    Ext.RegisterConsoleCommand("aposub", smokeConsoleSubCheck)
    Ext.RegisterConsoleCommand("aposubsweep", smokeConsoleSubSweep)
    Ext.RegisterConsoleCommand("apolist", smokeConsoleList)
    Ext.RegisterConsoleCommand("apowatch", smokeConsoleWatch)
    Ext.RegisterConsoleCommand("apofeature", smokeConsoleFeature)
    Ext.RegisterConsoleCommand("apofeatures", smokeConsoleFeatureList)
    Ext.RegisterConsoleCommand("apospawn", smokeConsoleSpawn)
    Ext.RegisterConsoleCommand("apospelllist", smokeConsoleSpellList)
    Ext.RegisterConsoleCommand("apospells", smokeConsoleSpells)
    Ext.RegisterConsoleCommand("apospell", smokeConsoleSpell)
    Log.Info("Smoke console commands registered: !aposmokehelp, !apowizmanifest, !apowizinteractive, !apowizcheck, !apowizautolevel, !apowizsweep, !aposub, !aposubsweep, !apolist, !apowatch, !apofeature, !apofeatures, !apospawn, !apospelllist, !apospells, !apospell")
else
    Log.Warn("Ext.RegisterConsoleCommand unavailable; REPL-only smoke entrypoints remain")
end

function Smoke.Wizard.Help()
    Log.Info("Wizard smoke commands:")
    Log.Info("  Apotheosis.Smoke.Wizard.RunSweep()")
    Log.Info("  Apotheosis.Smoke.Wizard.RunSweep(12, 20)")
    Log.Info("  Apotheosis.Smoke.Wizard.RunManifest('EvocationSchool')")
    Log.Info("  Apotheosis.Smoke.Wizard.RunManifest('AbjurationSchool')")
    Log.Info("  Apotheosis.Smoke.Wizard.RunManifest('DivinationSchool')")
    Log.Info("  Apotheosis.Smoke.Wizard.RunManifest('IllusionSchool')")
    Log.Info("  Apotheosis.Smoke.Wizard.RunManifest('BladesingingSchool')  [inferred]")
    Log.Info("  Apotheosis.Smoke.Wizard.RunManifestInteractive('EvocationSchool')")
    Log.Info("  Apotheosis.Smoke.Wizard.CheckLevel('EvocationSchool')        -- current host level")
    Log.Info("  Apotheosis.Smoke.Wizard.CheckLevel('EvocationSchool', 13)    -- explicit level")
    Log.Info("  Apotheosis.Smoke.Wizard.TryAutoLevel()")
    Log.Info("  !apowizmanifest EvocationSchool")
    Log.Info("  !apowizinteractive EvocationSchool")
    Log.Info("  !apowizcheck EvocationSchool 13")
    Log.Info("  !apowizautolevel")
    Log.Info("  !apowizsweep 12 20")
    Log.Info("  timing: " .. tostring(Smoke.LEVEL_SETTLE_MS) .. "ms after SetLevel, " .. tostring(Smoke.POST_RESTORE_SETTLE_MS) .. "ms after restore")
end

function Smoke.Help()
    Log.Info("Smoke commands:")
    Log.Info("  Apotheosis.Smoke.CaptureBuild()")
    Log.Info("  Apotheosis.Smoke.SetLevel(12)")
    Log.Info("  Apotheosis.Smoke.RunLevelSweep()")
    Log.Info("  Apotheosis.Smoke.RunLevelSweep(12, 20)")
    Log.Info("  Apotheosis.Smoke.Wizard.Help()")
    Log.Info("  Apotheosis.Smoke.Wizard.RunSweep()")
    Log.Info("  Apotheosis.Smoke.Wizard.RunManifest('SubclassName')")
    Log.Info("  Apotheosis.Smoke.Wizard.RunManifestInteractive('SubclassName')")
    Log.Info("  Apotheosis.Smoke.Wizard.CheckLevel('SubclassName', [Level])")
    Log.Info("  Apotheosis.Smoke.Wizard.TryAutoLevel()")
    Log.Info("  !aposmokehelp")
    Log.Info("  !apowizmanifest EvocationSchool")
    Log.Info("  !apowizinteractive EvocationSchool")
    Log.Info("  !apowizcheck EvocationSchool 13")
    Log.Info("  !apowizautolevel")
    Log.Info("  !apowizsweep 12 20")
    Log.Info("Generic (all classes/subclasses):")
    Log.Info("  !apolist                          -- list every known class/subclass")
    Log.Info("  !aposub <Name> [Level]            -- single-level check, e.g. !aposub ZealotPath 14")
    Log.Info("  !aposubsweep <Name> [start] [end] -- sweep 13-20, e.g. !aposubsweep EvocationSchool")
    Log.Info("Watch mode + functional tests:")
    Log.Info("  !apowatch on|off                  -- auto-validate every level-up (incl. moved sub-13 features)")
    Log.Info("  !apofeatures                      -- list functional feature tests + their target doctrine")
    Log.Info("  !apofeature <Passive> [TargetGuid] -- act-and-verify test, e.g. !apofeature WinterWalker_15_FrozenHaunt")
    Log.Info("  !apospawn <template> [faction]    -- stage a manual-test target, e.g. !apospawn wolf hostile")
end

Ext.Events.SessionLoaded:Subscribe(function()
    local ok, err = pcall(function()
        Log.Info("Smoke API ready - enter 'server' then Apotheosis.Smoke.Help() in the SE console")
        Log.Info("Smoke console shortcuts ready: !aposmokehelp, !apowizmanifest EvocationSchool, !apowizinteractive EvocationSchool, !apowizcheck EvocationSchool 13, !apowizautolevel, !apowizsweep 12 20")

        if AUTO_SMOKE.Enabled then
            Log.Warn("AUTO_SMOKE enabled: waiting for world-ready host before triggering")
            autoSmokeState.armed = true
            autoSmokeState.started = false
            autoSmokeState.tickCount = 0
            autoSmokeUnsubscribeTick()
            autoSmokeState.tickHandler = Ext.Events.Tick:Subscribe(autoSmokeStartWhenWorldReady)
        end
    end)
    if not ok then
        Log.Error("Smoke API readiness error: " .. tostring(err))
    end
end)
