-- AUTO-GENERATED by Scripts/build_all_class_expectations.py
-- DO NOT EDIT BY HAND.  Re-run the generator after Progressions.lsx changes.
-- Loaded by BootstrapServer.lua and exposed as _G.ApotheosisClassExpectations.

local M = { classes = {}, subclasses = {}, class_uuids = {}, subclass_uuids = {} }

M.class_uuids["114e7aee-d1d4-4371-8d90-8a2080592faf"] = "Cleric"
M.class_uuids["33bd368d-2ff4-4add-8692-66d87372053a"] = "Illrigger"
M.class_uuids["36be18ba-23db-4dff-bfa6-ae105ce43144"] = "Ranger"
M.class_uuids["457d0a6e-9da8-4f95-a225-18382f0e94b5"] = "Druid"
M.class_uuids["721dfac3-92d4-41f5-b773-b7072a86232f"] = "Fighter"
M.class_uuids["784001e2-c96d-4153-beb6-2adbef5abc92"] = "Sorcerer"
M.class_uuids["8aa2cf37-7739-4978-ab86-b1190b881620"] = "Artificer"
M.class_uuids["92cd50b6-eb1b-4824-8adb-853e90c34c90"] = "Bard"
M.class_uuids["a865965f-501b-46e9-9eaa-7748e8c04d09"] = "Wizard"
M.class_uuids["b4225a4b-4bbe-4d97-9e3c-4719dbd1487c"] = "Warlock"
M.class_uuids["b6cd23fa-ec1a-44a6-86c5-693201654dba"] = "Gunslinger"
M.class_uuids["c4598bdb-fc07-40dd-a62c-90cc138bd76f"] = "Monk"
M.class_uuids["d8cadb42-0ff9-4049-afaf-e5d78d06a399"] = "Barbarian"
M.class_uuids["e137179a-0c6f-4608-837a-322c13403943"] = "MonsterHunter"
M.class_uuids["e8b1eab0-ef11-40a2-8a0b-cee8d062bf2a"] = "Rogue"
M.class_uuids["ff4d9497-023c-434a-bd14-82fc367e991c"] = "Paladin"
M.subclass_uuids["0845c298-29fa-424b-b2be-b941345a5e90"] = "NobleGenies"
M.subclass_uuids["0a01dc6b-ab1a-4c0e-8a5e-4787fe1f2caf"] = "Champion"
M.subclass_uuids["0aa1cff9-c45f-4d00-a95b-99a7aa96dd06"] = "Hunter"
M.subclass_uuids["0da91e7c-7880-4cfa-819b-82eb6f41130f"] = "DanceCollege"
M.subclass_uuids["0e37e9bc-3909-49f4-8035-6d9736ad6867"] = "ZealotPath"
M.subclass_uuids["11576009-15e0-4cb2-b0ce-77dab572f106"] = "SanguineKnight"
M.subclass_uuids["14374d37-a70e-41a8-9dc5-85a23f8b5dd2"] = "WildMagicPath"
M.subclass_uuids["1c761ad0-6f5f-409e-ac1d-ddf6f85c1fc4"] = "Devotion"
M.subclass_uuids["1d23232f-cafb-4162-ac2a-a926fd6f734f"] = "PsiWarrior"
M.subclass_uuids["1e077f6b-1034-43ab-b54c-5718d78e9437"] = "Celestial"
M.subclass_uuids["22894c32-54cf-49ea-b366-44bfcf01bb2a"] = "FourElements"
M.subclass_uuids["2a5e3097-384c-4d29-8d6e-054fdfd26b80"] = "OpenHand"
M.subclass_uuids["2b46330d-0ada-4eb5-a131-3d250a41ca6a"] = "ValorCollege"
M.subclass_uuids["2e13292f-2fe2-4807-adae-d72bf04f020d"] = "OccultistGuild"
M.subclass_uuids["2e585948-d775-451d-b58b-15b75321d11e"] = "TotemWarriorPath"
M.subclass_uuids["32c7b8df-a6ec-4848-a9db-c0dce781beb9"] = "Thief"
M.subclass_uuids["32eee7d8-1b2f-4de5-b9ee-78fbd286c6ef"] = "BerserkerPath"
M.subclass_uuids["338cd823-6cec-434c-91ea-083ad535833f"] = "MoonCollege"
M.subclass_uuids["36286b0a-26f9-4b4e-9311-fd1404301d20"] = "DraconicBloodline"
M.subclass_uuids["3cc3d397-c47d-4966-87ae-88827f73f645"] = "Vengeance"
M.subclass_uuids["3d9e9113-46c7-4c81-bb20-93ad097588bc"] = "RuneKnight"
M.subclass_uuids["3eab0689-e51b-4634-a690-0375d3cb2716"] = "CircleOfTheMoon"
M.subclass_uuids["3f014425-480c-49d8-9b9d-2303543c0d11"] = "HighRoller"
M.subclass_uuids["42622d71-74af-409a-b821-85f270245fe2"] = "SpellfireSorcery"
M.subclass_uuids["436c9e1a-3a39-48dd-b753-7cee1bd19c00"] = "IllusionSchool"
M.subclass_uuids["46d31950-6917-444e-ac87-706702825215"] = "EnchantmentSchool"
M.subclass_uuids["499d1db7-129f-4416-b762-43675c43d0c9"] = "Painkiller"
M.subclass_uuids["4b5da2f5-b999-4623-8bff-a63df5560fb3"] = "LifeDomain"
M.subclass_uuids["4d73bb8e-5405-4586-9947-0cda0e2f424b"] = "CircleOfTheSea"
M.subclass_uuids["5764faec-f81c-4708-a652-15b3459715e8"] = "Soulknife"
M.subclass_uuids["6fd9547d-cc28-400e-bfa9-3a85baa70f24"] = "BeastMaster"
M.subclass_uuids["733ddf8c-9ec4-4c5a-85e3-c70fd3df3c24"] = "Archfey"
M.subclass_uuids["7458da78-34b7-4150-a42f-37197ab04510"] = "CircleOfTheLand"
M.subclass_uuids["7577b0e1-a517-4f82-8f72-05a227dc5e88"] = "DivinationSchool"
M.subclass_uuids["7a3feb8d-dda7-46ec-9029-1f302f537432"] = "ConjurationSchool"
M.subclass_uuids["8047cf29-2c79-4f12-a4bf-d965a023be63"] = "BladesingingSchool"
M.subclass_uuids["8866db28-7dda-4fd6-93ed-20eca16314f0"] = "Fiend"
M.subclass_uuids["886e988c-1d77-43ad-a0a9-f1e48c56d29b"] = "ClockworkSorcery"
M.subclass_uuids["9b1afbf5-2133-4042-b39e-dfbade27a60b"] = "Artillerist"
M.subclass_uuids["9d4ed957-c140-4955-89a6-56b8cb5313ee"] = "Shadowmaster"
M.subclass_uuids["a06241d2-c432-472c-8c7d-84228d530cfa"] = "GlamourCollege"
M.subclass_uuids["a12f2924-30b4-4185-9db9-2c5b383ff449"] = "TransmutationSchool"
M.subclass_uuids["aa644f08-d368-40d3-802a-b3bce31cd4e8"] = "GraveDomain"
M.subclass_uuids["ab2f7820-cb6b-49e4-804a-820d25291a16"] = "Alchemist"
M.subclass_uuids["acb94255-2c1e-4472-a707-4b58d183428f"] = "Mercy"
M.subclass_uuids["b36d247e-d39f-4ae9-9476-3ec315c55789"] = "Ancients"
M.subclass_uuids["b53a8061-f31d-4985-adfe-d4d691a918d9"] = "Assassin"
M.subclass_uuids["b722614a-303f-411a-bb19-a1882ad1f4cc"] = "EldritchKnight"
M.subclass_uuids["b81df0a8-5ecb-43b5-abd9-39b9a244561c"] = "Glory"
M.subclass_uuids["b927a22a-d64b-48d6-bc7c-38c5f7f6a061"] = "DeathDomain"
M.subclass_uuids["b9ccf90e-b35b-4b73-b896-8ed2d32ae8c6"] = "WarDomain"
M.subclass_uuids["ba0844e2-726c-4e39-b6f7-c46733df19c4"] = "ArchitectOfRuin"
M.subclass_uuids["bebbfa54-1ad1-4459-b11b-8755e8633c5a"] = "DevourerGuild"
M.subclass_uuids["bf46d73f-d406-4cb8-9a1d-e6e758ca02c7"] = "Shadow"
M.subclass_uuids["c059dca1-c17d-4dce-8260-83ede5070eac"] = "EvocationSchool"
M.subclass_uuids["c2f64e7b-124f-4b2d-9dcb-bbeeef2d747e"] = "FeyWanderer"
M.subclass_uuids["c4bd5252-d68a-4330-9431-5e8ab24c5f29"] = "SwordsCollege"
M.subclass_uuids["c54d7591-b305-4f22-b2a7-1bf5c4a3470a"] = "LightDomain"
M.subclass_uuids["d21368ac-c776-465c-9dcf-6123dd52734f"] = "LoreCollege"
M.subclass_uuids["d215aa58-a49c-4e43-ad94-ccabe49dcdaa"] = "WhiteHat"
M.subclass_uuids["d5f10e55-84e3-409b-aa64-2098c9550319"] = "GloomStalker"
M.subclass_uuids["d6db66be-cc60-4ebd-bf63-2a856bbfedaf"] = "WorldTreePath"
M.subclass_uuids["d84e3f76-0e56-4344-9454-ba167a286bdb"] = "CarverGuild"
M.subclass_uuids["d9c984db-15cb-4308-88be-fb88cf3e8c32"] = "Armorer"
M.subclass_uuids["e1e4a21f-9405-46ec-81a0-ccc8d58d9736"] = "GreatOldOne"
M.subclass_uuids["e668c6f1-5149-4b10-ab7e-3637ed444066"] = "BattleMaster"
M.subclass_uuids["e6a0eb75-7a01-4f40-8563-24ba2615e99b"] = "AbjurationSchool"
M.subclass_uuids["ebe18794-b5e1-41c4-befa-4b9d6922b0ec"] = "KnowledgeDomain"
M.subclass_uuids["ede4778e-7602-440f-9075-b4bc8dc31cea"] = "ArcaneTrickster"
M.subclass_uuids["ee5a89b5-21c6-419e-8b30-aecf929bd7d7"] = "AberrantSorcery"
M.subclass_uuids["eeb1f97b-7cc4-4720-b2a8-bf8cbb4dc76e"] = "ScionThree"
M.subclass_uuids["f013d01b-3310-43f7-81bf-a51130442b5e"] = "TrickeryDomain"
M.subclass_uuids["f507f7bc-3d1a-4034-9590-ddef5a05d5b3"] = "PurpleDragonKnight"
M.subclass_uuids["f574d2d6-cfc2-4cda-8771-1917f1eabaf1"] = "BattleSmith"
M.subclass_uuids["f576dd16-d230-4233-bf3e-1d5ed0106b0c"] = "Hellspeaker"
M.subclass_uuids["f617ec08-b29d-4ac0-a742-3fd6c25c4520"] = "Spellslinger"
M.subclass_uuids["fbb8347b-20e3-4846-ba91-0552cd12fc5f"] = "NecromancySchool"
M.subclass_uuids["fbf9d94c-9175-4145-9bd9-645dec6d4f1d"] = "WinterWalker"
M.subclass_uuids["fe416267-36f0-4346-90fc-4aeb7f25ec07"] = "CircleOfStars"

M.classes["Artificer"] = {
    levels = {
        [13] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,4)",
            selectors = "AddSpells(ee537fcf-8372-502b-ba07-a0887575e49f)",
        },
        [14] = {
            passives  = { "Artificer_14_AdvancedArtifice" },
        },
        [15] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,4)",
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,4);ActionResource(SpellSlot,1,5)",
            selectors = "AddSpells(dfb36751-25c2-59d2-a021-69cdac534724)",
        },
        [18] = {
            passives  = { "Artificer_MagicItemMaster" },
        },
        [19] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,5)",
        },
        [20] = {
            passives  = { "Artificer_SoulOfArtifice" },
        },
    },
}

M.classes["Barbarian"] = {
    levels = {
        [12] = {
            passives  = {},
            boosts    = "ActionResource(Rage,1,0)",
        },
        [13] = {
            passives  = { "Barbarian_BrutalStrike_Improved" },
            boosts    = "ActionResource(RageCharge,1,0)",
        },
        [14] = {
            passives  = {},
        },
        [15] = {
            passives  = { "Barbarian_PersistentRage" },
        },
        [16] = {
            passives  = {},
            boosts    = "ActionResource(RageCharge,1,0)",
        },
        [17] = {
            passives  = { "Barbarian_BrutalStrike_17" },
        },
        [18] = {
            passives  = { "Barbarian_IndomitableMight" },
            boosts    = "ActionResource(RageCharge,1,0)",
        },
        [19] = {
            passives  = {},
            selectors = "SelectPassives(23b18ae7-dc54-5b4f-8939-a9af322e3cef,1,EpicBoon);SelectPassives(4ef62eb1-4735-5e99-8568-dc013af9df15,1,EpicBoonAbility)",
        },
        [20] = {
            passives  = { "Barbarian_PrimalChampion" },
        },
    },
}

M.classes["Bard"] = {
    levels = {
        [13] = {
            passives  = { "UnlockedSpellSlotLevel7" },
            boosts    = "ActionResource(SpellSlot,1,7)",
            selectors = "SelectSpells(858d4322-9e9f-4aa4-aada-9c68835dc6fe,1,1,BardMagicalSecrets);SelectSpells(00170001-0001-0001-0001-000000000005,1,1,BardSpells)",
        },
        [14] = {
            passives  = {},
        },
        [15] = {
            passives  = { "UnlockedSpellSlotLevel8" },
            boosts    = "ActionResource(SpellSlot,1,8)",
            selectors = "SelectSpells(858d4322-9e9f-4aa4-aada-9c68835dc6fe,1,1,BardMagicalSecrets);SelectSpells(00180001-0001-0001-0001-000000000005,1,1,BardSpells)",
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = { "UnlockedSpellSlotLevel9" },
            boosts    = "ActionResource(SpellSlot,1,9)",
            selectors = "SelectSpells(858d4322-9e9f-4aa4-aada-9c68835dc6fe,1,1,BardMagicalSecrets);SelectSpells(00190001-0001-0001-0001-000000000005,1,1,BardSpells)",
        },
        [18] = {
            passives  = { "Bard_SuperiorInspiration" },
            boosts    = "ActionResource(SpellSlot,1,5);ActionResource(BardicInspiration,1,0)",
            selectors = "SelectSpells(858d4322-9e9f-4aa4-aada-9c68835dc6fe,1,1,BardMagicalSecrets);SelectSpells(00190001-0001-0001-0001-000000000005,1,1,BardSpells)",
        },
        [19] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,6)",
            selectors = "SelectSpells(858d4322-9e9f-4aa4-aada-9c68835dc6fe,1,1,BardMagicalSecrets);SelectSpells(00190001-0001-0001-0001-000000000005,1,1,BardSpells);SelectPassives(23b18ae7-dc54-5b4f-8939-a9af322e3cef,1,EpicBoon);SelectPassives(4ef62eb1-4735-5e99-8568-dc013af9df15,1,EpicBoonAbility)",
        },
        [20] = {
            passives  = { "Bard_WordsOfCreation" },
            boosts    = "ActionResource(SpellSlot,1,7)",
            selectors = "SelectSpells(858d4322-9e9f-4aa4-aada-9c68835dc6fe,1,1,BardMagicalSecrets);SelectSpells(00190001-0001-0001-0001-000000000005,1,1,BardSpells)",
        },
    },
}

M.classes["Cleric"] = {
    levels = {
        [12] = {
            passives  = {},
        },
        [13] = {
            passives  = { "UnlockedSpellSlotLevel7" },
            boosts    = "ActionResource(SpellSlot,1,7)",
            selectors = "AddSpells(00170001-0001-0001-0001-000000000003)",
        },
        [14] = {
            passives  = { "ImprovedBlessedStrikes" },
        },
        [15] = {
            passives  = { "UnlockedSpellSlotLevel8" },
            boosts    = "ActionResource(SpellSlot,1,8)",
            selectors = "AddSpells(00180001-0001-0001-0001-000000000003)",
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = { "UnlockedSpellSlotLevel9" },
            boosts    = "ActionResource(SpellSlot,1,9)",
            selectors = "AddSpells(00190001-0001-0001-0001-000000000003)",
        },
        [18] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,5);ActionResource(ChannelDivinity,1,0)",
        },
        [19] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,6)",
            selectors = "SelectPassives(23b18ae7-dc54-5b4f-8939-a9af322e3cef,1,EpicBoon);SelectPassives(4ef62eb1-4735-5e99-8568-dc013af9df15,1,EpicBoonAbility)",
        },
        [20] = {
            passives  = { "Cleric_GreaterDivineIntervention" },
            boosts    = "ActionResource(SpellSlot,1,7)",
        },
    },
}

M.classes["Druid"] = {
    levels = {
        [13] = {
            passives  = { "UnlockedSpellSlotLevel7" },
            boosts    = "ActionResource(SpellSlot,1,7)",
            selectors = "AddSpells(00170001-0001-0001-0001-000000000004)",
        },
        [14] = {
            passives  = {},
        },
        [15] = {
            passives  = { "Druid_ImprovedElementalFury", "UnlockedSpellSlotLevel8" },
            boosts    = "ActionResource(SpellSlot,1,8)",
            selectors = "AddSpells(00180001-0001-0001-0001-000000000004)",
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = { "UnlockedSpellSlotLevel9" },
            boosts    = "ActionResource(SpellSlot,1,9)",
            selectors = "AddSpells(00190001-0001-0001-0001-000000000004)",
        },
        [18] = {
            passives  = { "Druid_BeastSpells" },
            boosts    = "ActionResource(SpellSlot,1,5)",
        },
        [19] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,6)",
            selectors = "SelectPassives(23b18ae7-dc54-5b4f-8939-a9af322e3cef,1,EpicBoon);SelectPassives(4ef62eb1-4735-5e99-8568-dc013af9df15,1,EpicBoonAbility)",
        },
        [20] = {
            passives  = { "Druid_Archdruid" },
            boosts    = "ActionResource(SpellSlot,1,7);ActionResource(WildShape,100,0)",
        },
    },
}

M.classes["Fighter"] = {
    levels = {
        [13] = {
            passives  = { "Fighter_StudiedAttacks" },
            boosts    = "ActionResource(Indomitable_Charge,1,0)",
        },
        [14] = {
            passives  = {},
        },
        [15] = {
            passives  = {},
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = {},
            boosts    = "ActionResource(ActionSurge,1,0);ActionResource(Indomitable_Charge,1,0)",
        },
        [18] = {
            passives  = {},
        },
        [19] = {
            passives  = {},
            selectors = "SelectPassives(23b18ae7-dc54-5b4f-8939-a9af322e3cef,1,EpicBoon);SelectPassives(4ef62eb1-4735-5e99-8568-dc013af9df15,1,EpicBoonAbility)",
        },
        [20] = {
            passives  = { "ExtraAttack_3" },
        },
    },
}

M.classes["Gunslinger"] = {
    levels = {
        [13] = {
            passives  = { "Gunslinger_13_CheatDeath" },
        },
        [14] = {
            passives  = {},
            boosts    = "ActionResource(Risk,1,0)",
        },
        [15] = {
            passives  = { "Gunslinger_15_DireGambit", "Gunslinger_15_DireGambit_Initiative" },
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = { "Gunslinger_17_CriticalShot" },
        },
        [18] = {
            passives  = { "Gunslinger_18_DeftManeuver" },
        },
        [19] = {
            passives  = {},
            boosts    = "ActionResource(HitPointDice08,1,0);",
            selectors = "SelectPassives(23b18ae7-dc54-5b4f-8939-a9af322e3cef,1,EpicBoon);SelectPassives(4ef62eb1-4735-5e99-8568-dc013af9df15,1,EpicBoonAbility)",
        },
        [20] = {
            passives  = { "Gunslinger_20_Headshot" },
        },
    },
}

M.classes["Illrigger"] = {
    levels = {
        [13] = {
            passives  = {},
            boosts    = "ActionResource(Seal,1,0)",
            selectors = "SelectPassives(e2e21374-e6e1-51cd-b67a-67ea2811dff7,1,IllriggerInterdiction)",
        },
        [14] = {
            passives  = { "Illrigger_14_SuperiorInterdict" },
        },
        [15] = {
            passives  = {},
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = { "Illrigger_17_InfernalMajesty" },
        },
        [18] = {
            passives  = {},
            boosts    = "ActionResource(Seal,1,0)",
            selectors = "SelectPassives(e2e21374-e6e1-51cd-b67a-67ea2811dff7,1,IllriggerInterdiction)",
        },
        [19] = {
            passives  = {},
        },
        [20] = {
            passives  = { "Illrigger_20_MasterOfHell" },
        },
    },
}

M.classes["Monk"] = {
    levels = {
        [13] = {
            passives  = { "Monk_DeflectEnergy" },
            boosts    = "ActionResource(KiPoint,1,0)",
        },
        [14] = {
            passives  = { "Monk_DisciplinedSurvivor" },
            boosts    = "ActionResource(KiPoint,1,0)",
        },
        [15] = {
            passives  = { "Monk_PerfectFocus" },
            boosts    = "ActionResource(KiPoint,1,0)",
        },
        [16] = {
            passives  = {},
            boosts    = "ActionResource(KiPoint,1,0)",
        },
        [17] = {
            passives  = {},
            boosts    = "ActionResource(KiPoint,1,0)",
        },
        [18] = {
            passives  = { "Monk_SuperiorDefense" },
            boosts    = "ActionResource(KiPoint,1,0)",
        },
        [19] = {
            passives  = {},
            boosts    = "ActionResource(KiPoint,1,0)",
            selectors = "SelectPassives(23b18ae7-dc54-5b4f-8939-a9af322e3cef,1,EpicBoon);SelectPassives(4ef62eb1-4735-5e99-8568-dc013af9df15,1,EpicBoonAbility)",
        },
        [20] = {
            passives  = { "Monk_BodyAndMind" },
            boosts    = "ActionResource(KiPoint,1,0);Ability(Dexterity,2,22);Ability(Wisdom,2,22)",
        },
    },
}

M.classes["MonsterHunter"] = {
    levels = {
        [13] = {
            passives  = { "MonsterHunter_13_LethalQuarry" },
        },
        [14] = {
            passives  = {},
        },
        [15] = {
            passives  = { "MonsterHunter_15_PrimalAccuracy" },
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = { "MonsterHunter_17_HardenedResolve" },
        },
        [18] = {
            passives  = { "MonsterHunter_18_ApexPredator" },
        },
        [19] = {
            passives  = {},
        },
        [20] = {
            passives  = { "MonsterHunter_20_MasterHunter" },
        },
    },
}

M.classes["Paladin"] = {
    levels = {
        [13] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,4)",
            selectors = "AddSpells(b88aff43-b75a-5947-b283-3c6ca5bf2591)",
        },
        [14] = {
            passives  = { "Paladin_14_RestoringTouch" },
        },
        [15] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,4)",
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,4);ActionResource(SpellSlot,1,5)",
            selectors = "AddSpells(bce36493-022a-5a20-8b8d-fd97f89be9a7)",
        },
        [18] = {
            passives  = { "Paladin_Aura30ft" },
        },
        [19] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,5)",
            selectors = "SelectPassives(23b18ae7-dc54-5b4f-8939-a9af322e3cef,1,EpicBoon);SelectPassives(4ef62eb1-4735-5e99-8568-dc013af9df15,1,EpicBoonAbility)",
        },
        [20] = {
            passives  = {},
        },
    },
}

M.classes["Ranger"] = {
    levels = {
        [13] = {
            passives  = { "Ranger_RelentlessHunter" },
            boosts    = "ActionResource(SpellSlot,1,4)",
            selectors = "AddSpells(6e77d7ac-4b79-5691-bde3-357017ad4cdc)",
        },
        [14] = {
            passives  = { "Ranger_14_NaturesVeil" },
        },
        [15] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,4)",
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = { "Ranger_17_PreciseHunter" },
            boosts    = "ActionResource(SpellSlot,1,4);ActionResource(SpellSlot,1,5)",
            selectors = "AddSpells(6b625ece-306d-576a-9fa2-896d884e4e05)",
        },
        [18] = {
            passives  = { "Ranger_FeralSenses" },
        },
        [19] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,5)",
            selectors = "SelectPassives(23b18ae7-dc54-5b4f-8939-a9af322e3cef,1,EpicBoon);SelectPassives(4ef62eb1-4735-5e99-8568-dc013af9df15,1,EpicBoonAbility)",
        },
        [20] = {
            passives  = { "Ranger_FoeSlayer" },
        },
    },
}

M.classes["Rogue"] = {
    levels = {
        [13] = {
            passives  = {},
        },
        [14] = {
            passives  = {},
        },
        [15] = {
            passives  = { "Rogue_SlipperyMind" },
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = {},
        },
        [18] = {
            passives  = { "Rogue_Elusive" },
        },
        [19] = {
            passives  = {},
            selectors = "SelectPassives(23b18ae7-dc54-5b4f-8939-a9af322e3cef,1,EpicBoon);SelectPassives(4ef62eb1-4735-5e99-8568-dc013af9df15,1,EpicBoonAbility)",
        },
        [20] = {
            passives  = { "Rogue_StrokeOfLuck" },
        },
    },
}

M.classes["Sorcerer"] = {
    levels = {
        [13] = {
            passives  = { "UnlockedSpellSlotLevel7" },
            boosts    = "ActionResource(SpellSlot,1,7);ActionResource(SorceryPoint,1,0)",
            selectors = "SelectSpells(00170001-0001-0001-0001-000000000002,1,0,SorcererSpell)",
        },
        [14] = {
            passives  = {},
            boosts    = "ActionResource(SorceryPoint,1,0)",
            selectors = "SelectSpells(00170001-0001-0001-0001-000000000002,1,0,SorcererSpell)",
        },
        [15] = {
            passives  = { "UnlockedSpellSlotLevel8" },
            boosts    = "ActionResource(SpellSlot,1,8);ActionResource(SorceryPoint,1,0)",
            selectors = "SelectSpells(00180001-0001-0001-0001-000000000002,1,0,SorcererSpell)",
        },
        [16] = {
            passives  = {},
            boosts    = "ActionResource(SorceryPoint,1,0)",
        },
        [17] = {
            passives  = { "UnlockedSpellSlotLevel9" },
            boosts    = "ActionResource(SpellSlot,1,9);ActionResource(SorceryPoint,1,0)",
            selectors = "SelectSpells(00190001-0001-0001-0001-000000000002,1,0,SorcererSpell);SelectPassives(c3506532-36eb-4d18-823e-497a537a9619,1,Metamagic)",
        },
        [18] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,5);ActionResource(SorceryPoint,1,0)",
        },
        [19] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,6);ActionResource(SorceryPoint,1,0)",
            selectors = "SelectPassives(23b18ae7-dc54-5b4f-8939-a9af322e3cef,1,EpicBoon);SelectPassives(4ef62eb1-4735-5e99-8568-dc013af9df15,1,EpicBoonAbility)",
        },
        [20] = {
            passives  = { "Sorcerer_ArcaneApotheosis" },
            boosts    = "ActionResource(SpellSlot,1,7);ActionResource(SorceryPoint,1,0)",
        },
    },
}

M.classes["Warlock"] = {
    levels = {
        [13] = {
            passives  = { "Warlock_MysticArcanum_7" },
            selectors = "SelectSpells(00170001-0001-0001-0001-000000000007,1,0,MysticArcanum7)",
        },
        [14] = {
            passives  = {},
        },
        [15] = {
            passives  = { "Warlock_MysticArcanum_8" },
            selectors = "SelectSpells(00180001-0001-0001-0001-000000000007,1,0,MysticArcanum8);SelectPassives(ab56f79f-95ec-48e5-bd83-e80ba9afc844,1,WarlockInvocations)",
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = { "Warlock_MysticArcanum_9" },
            selectors = "SelectSpells(00190001-0001-0001-0001-000000000007,1,0,MysticArcanum9)",
        },
        [18] = {
            passives  = {},
            selectors = "SelectPassives(ab56f79f-95ec-48e5-bd83-e80ba9afc844,1,WarlockInvocations)",
        },
        [19] = {
            passives  = {},
            selectors = "SelectPassives(23b18ae7-dc54-5b4f-8939-a9af322e3cef,1,EpicBoon);SelectPassives(4ef62eb1-4735-5e99-8568-dc013af9df15,1,EpicBoonAbility)",
        },
        [20] = {
            passives  = { "Warlock_EldritchMaster" },
        },
    },
}

M.classes["Wizard"] = {
    levels = {
        [13] = {
            passives  = { "UnlockedSpellSlotLevel7" },
            boosts    = "ActionResource(SpellSlot,1,7)",
            selectors = "SelectSpells(aa384b4e-36b4-5b2d-93b3-c1063ba2ffb2,2,0,WizardSpellList)",
        },
        [14] = {
            passives  = {},
            selectors = "SelectSpells(aa384b4e-36b4-5b2d-93b3-c1063ba2ffb2,2,0,WizardSpellList)",
        },
        [15] = {
            passives  = { "UnlockedSpellSlotLevel8" },
            boosts    = "ActionResource(SpellSlot,1,8)",
            selectors = "SelectSpells(f0f0369f-fef5-5399-92c1-0a02c56c93bd,2,0,WizardSpellList)",
        },
        [16] = {
            passives  = {},
            selectors = "SelectSpells(f0f0369f-fef5-5399-92c1-0a02c56c93bd,2,0,WizardSpellList)",
        },
        [17] = {
            passives  = { "UnlockedSpellSlotLevel9" },
            boosts    = "ActionResource(SpellSlot,1,9)",
            selectors = "SelectSpells(ae03c25e-d0ac-55a5-899a-ae75a3b20c5a,2,0,WizardSpellList)",
        },
        [18] = {
            passives  = { "SpellMastery" },
            boosts    = "ActionResource(SpellSlot,1,5)",
            selectors = "SelectSpells(ae03c25e-d0ac-55a5-899a-ae75a3b20c5a,2,0,WizardSpellList)",
        },
        [19] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,6)",
            selectors = "SelectSpells(ae03c25e-d0ac-55a5-899a-ae75a3b20c5a,2,0,WizardSpellList);SelectPassives(23b18ae7-dc54-5b4f-8939-a9af322e3cef,1,EpicBoon);SelectPassives(4ef62eb1-4735-5e99-8568-dc013af9df15,1,EpicBoonAbility)",
        },
        [20] = {
            passives  = { "Wizard_SignatureSpells" },
            boosts    = "ActionResource(SpellSlot,1,7);ActionResource(SignatureSpellCharge,2,0)",
            selectors = "SelectSpells(ae03c25e-d0ac-55a5-899a-ae75a3b20c5a,2,0,WizardSpellList)",
        },
    },
}

M.subclasses["AberrantSorcery"] = {
    parent = "Sorcerer",
    levels = {
        [14] = {
            passives  = { "AberrantSorcery_14_RevelationInFlesh" },
        },
        [18] = {
            passives  = { "AberrantSorcery_18_WarpingImplosion" },
        },
    },
}

M.subclasses["AbjurationSchool"] = {
    parent = "Wizard",
    levels = {
        [13] = {
            passives  = {},
            selectors = "SelectSpells(f822dc38-632c-5941-be44-41b1faba1b79,1,0,Wizard_3_Savant)",
        },
        [14] = {
            passives  = { "Abjurer_14_SpellResistance" },
        },
        [15] = {
            passives  = {},
            selectors = "SelectSpells(c75214de-c712-54e8-9a6f-1396417c7c29,1,0,Wizard_3_Savant)",
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = {},
            selectors = "SelectSpells(6646e188-0f92-51d0-9a15-84398e066b0f,1,0,Wizard_3_Savant)",
        },
        [18] = {
            passives  = {},
        },
        [19] = {
            passives  = {},
        },
        [20] = {
            passives  = {},
        },
    },
}

M.subclasses["Alchemist"] = {
    parent = "Artificer",
    levels = {
        [15] = {
            passives  = { "Alchemist_15_ChemicalMastery" },
        },
    },
}

M.subclasses["Ancients"] = {
    parent = "Paladin",
    levels = {
        [15] = {
            passives  = { "Ancients_15_UndyingSentinel" },
        },
        [20] = {
            passives  = { "Ancients_20_ElderChampion" },
        },
    },
}

M.subclasses["ArcaneTrickster"] = {
    parent = "Rogue",
    levels = {
        [11] = {
            passives  = {},
        },
        [13] = {
            passives  = { "ArcaneTrickster_VersatileTrickster" },
        },
        [17] = {
            passives  = { "ArcaneTrickster_11_SpellThief" },
        },
    },
}

M.subclasses["Archfey"] = {
    parent = "Warlock",
    levels = {
        [14] = {
            passives  = { "Archfey_14_BewitchingMagic" },
        },
    },
}

M.subclasses["ArchitectOfRuin"] = {
    parent = "Illrigger",
    levels = {
        [13] = {
            passives  = { "ArchitectOfRuin_13_Spellbreaker" },
            boosts    = "ActionResource(SpellSlot,2,3)",
            selectors = "SelectSpells(22755771-ca11-49f4-b772-13d8b8fecd93,1,1,EldritchKnightAbjEvo)",
        },
        [14] = {
            passives  = {},
            selectors = "SelectSpells(22755771-ca11-49f4-b772-13d8b8fecd93,1,1,EldritchKnightAbjEvo)",
        },
        [15] = {
            passives  = { "ArchitectsOfRuin_15_VileTransmogrification" },
        },
        [16] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,3)",
            selectors = "SelectSpells(22755771-ca11-49f4-b772-13d8b8fecd93,1,1,EldritchKnightAbjEvo)",
        },
        [18] = {
            passives  = { "ArchitectOfRuin_18_HellMage" },
        },
        [19] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,4)",
            selectors = "SelectSpells(820b1220-0385-426d-ae15-458dc8a6f5c0,1,1,EldritchKnightAbjEvo)",
        },
        [20] = {
            passives  = {},
            selectors = "SelectSpells(820b1220-0385-426d-ae15-458dc8a6f5c0,1,1,EldritchKnightAbjEvo)",
        },
    },
}

M.subclasses["Armorer"] = {
    parent = "Artificer",
    levels = {
        [15] = {
            passives  = { "Armorer_15_PerfectedArmor" },
        },
    },
}

M.subclasses["Artillerist"] = {
    parent = "Artificer",
    levels = {
        [15] = {
            passives  = { "Artillerist_15_FortifiedPosition" },
        },
    },
}

M.subclasses["Assassin"] = {
    parent = "Rogue",
    levels = {
        [11] = {
            passives  = {},
        },
        [13] = {
            passives  = { "Assassin_13_EnvenomWeapons" },
        },
        [17] = {
            passives  = { "Assassin_11_DeathStrike" },
        },
    },
}

M.subclasses["BattleMaster"] = {
    parent = "Fighter",
    levels = {
        [15] = {
            passives  = { "BattleMaster_Relentless" },
            boosts    = "ActionResource(SuperiorityDie,1,0)",
            selectors = "SelectPassives(e51a2ef5-3663-43f9-8e74-5e28520323f1,2,Maneuvers)",
        },
        [18] = {
            passives  = { "BattleMaster_UltimateCombatSuperiority" },
        },
    },
}

M.subclasses["BattleSmith"] = {
    parent = "Artificer",
    levels = {
        [15] = {
            passives  = { "BattleSmith_15_ImprovedDefender" },
        },
    },
}

M.subclasses["BeastMaster"] = {
    parent = "Ranger",
    levels = {
        [15] = {
            passives  = { "BeastMaster_15_ShareSpells" },
        },
    },
}

M.subclasses["BerserkerPath"] = {
    parent = "Barbarian",
    levels = {
        [14] = {
            passives  = { "Berserker_14_IntimidatingPresence" },
        },
    },
}

M.subclasses["BladesingingSchool"] = {
    parent = "Wizard",
    levels = {
        [12] = {
            passives  = {},
        },
        [13] = {
            passives  = {},
        },
        [14] = {
            passives  = { "SongVictory" },
        },
        [15] = {
            passives  = {},
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = {},
        },
        [18] = {
            passives  = {},
        },
        [19] = {
            passives  = {},
        },
        [20] = {
            passives  = {},
        },
    },
}

M.subclasses["CarverGuild"] = {
    parent = "MonsterHunter",
    levels = {
        [15] = {
            passives  = { "CarverGuild_15_Bulwark" },
        },
        [18] = {
            passives  = { "CarverGuild_18_Executioner" },
        },
    },
}

M.subclasses["Celestial"] = {
    parent = "Warlock",
    levels = {
        [14] = {
            passives  = { "Celestial_14_SearingVengeance" },
        },
    },
}

M.subclasses["Champion"] = {
    parent = "Fighter",
    levels = {
        [12] = {
            passives  = {},
        },
        [15] = {
            passives  = { "SuperiorCritical" },
        },
        [18] = {
            passives  = { "Champion_Survivor" },
        },
    },
}

M.subclasses["CircleOfStars"] = {
    parent = "Druid",
    levels = {
        [14] = {
            passives  = { "CircleOfStars_14_FullOfStars" },
        },
    },
}

M.subclasses["CircleOfTheLand"] = {
    parent = "Druid",
    levels = {
        [14] = {
            passives  = { "CircleOfTheLand_14_NaturesSanctuary" },
        },
    },
}

M.subclasses["CircleOfTheMoon"] = {
    parent = "Druid",
    levels = {
        [14] = {
            passives  = { "CircleOfTheMoon_14_LunarForm" },
        },
    },
}

M.subclasses["CircleOfTheSea"] = {
    parent = "Druid",
    levels = {
        [14] = {
            passives  = { "CircleOfTheSea_14_OceanicGift" },
        },
    },
}

M.subclasses["ClockworkSorcery"] = {
    parent = "Sorcerer",
    levels = {
        [11] = {
            passives  = {},
        },
        [14] = {
            passives  = { "TranceOfOrder" },
        },
        [18] = {
            passives  = { "ClockworkSorcery_18_ClockworkCavalcade" },
        },
    },
}

M.subclasses["ConjurationSchool"] = {
    parent = "Wizard",
    levels = {
        [13] = {
            passives  = {},
            selectors = "SelectSpells(994b2dda-8268-5707-923c-426fab5888aa,1,0,Wizard_3_Savant)",
        },
        [14] = {
            passives  = { "Conjurer_14_SplinteredSummons" },
        },
        [15] = {
            passives  = {},
            selectors = "SelectSpells(966b2e22-b9a6-552c-aecf-341a006b5b3c,1,0,Wizard_3_Savant)",
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = {},
            selectors = "SelectSpells(3f0b958f-6e36-599a-8f27-1741c627f4c8,1,0,Wizard_3_Savant)",
        },
        [18] = {
            passives  = {},
        },
        [19] = {
            passives  = {},
        },
        [20] = {
            passives  = {},
        },
    },
}

M.subclasses["DanceCollege"] = {
    parent = "Bard",
    levels = {
        [12] = {
            passives  = {},
        },
        [14] = {
            passives  = { "Evasion" },
        },
    },
}

M.subclasses["DeathDomain"] = {
    parent = "Cleric",
    levels = {
        [17] = {
            passives  = { "DeathDomain_17_ImprovedReaper" },
        },
    },
}

M.subclasses["Devotion"] = {
    parent = "Paladin",
    levels = {
        [15] = {
            passives  = { "Devotion_15_SmiteOfProtection" },
        },
        [20] = {
            passives  = { "Devotion_20_HolyNimbus" },
        },
    },
}

M.subclasses["DevourerGuild"] = {
    parent = "MonsterHunter",
    levels = {
        [15] = {
            passives  = { "DevourerGuild_15_RavenousMight" },
        },
        [18] = {
            passives  = { "DevourerGuild_18_ApexMetabolism" },
        },
    },
}

M.subclasses["DivinationSchool"] = {
    parent = "Wizard",
    levels = {
        [13] = {
            passives  = {},
        },
        [14] = {
            passives  = { "Diviner_14_GreaterPortent" },
        },
        [15] = {
            passives  = {},
            selectors = "SelectSpells(b4b9171b-9285-51a9-aec1-837b32900208,1,0,Wizard_3_Savant)",
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = {},
            selectors = "SelectSpells(93babf2a-9660-53f2-ba40-de3b6b67510f,1,0,Wizard_3_Savant)",
        },
        [18] = {
            passives  = {},
        },
        [19] = {
            passives  = {},
        },
        [20] = {
            passives  = {},
        },
    },
}

M.subclasses["DraconicBloodline"] = {
    parent = "Sorcerer",
    levels = {
        [14] = {
            passives  = { "DraconicBloodline_14_DragonWings" },
        },
        [18] = {
            passives  = { "DraconicBloodline_18_DragonCompanion" },
            boosts    = "ActionResource(DraconicSpiritCharge,1,0)",
        },
    },
}

M.subclasses["EldritchKnight"] = {
    parent = "Fighter",
    levels = {
        [12] = {
            passives  = {},
        },
        [15] = {
            passives  = { "ArcaneCharge" },
        },
        [18] = {
            passives  = { "EldritchKnight_ImprovedWarMagic" },
        },
    },
}

M.subclasses["EnchantmentSchool"] = {
    parent = "Wizard",
    levels = {
        [13] = {
            passives  = {},
        },
        [14] = {
            passives  = { "Enchanter_14_AlterMemories" },
        },
        [15] = {
            passives  = {},
            selectors = "SelectSpells(532952f7-a1a2-5daa-97d2-661d5dba3315,1,0,Wizard_3_Savant)",
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = {},
            selectors = "SelectSpells(86ecd0f1-fd52-5e6a-97cf-a8e28cb12951,1,0,Wizard_3_Savant)",
        },
        [18] = {
            passives  = {},
        },
        [19] = {
            passives  = {},
        },
        [20] = {
            passives  = {},
        },
    },
}

M.subclasses["EvocationSchool"] = {
    parent = "Wizard",
    levels = {
        [13] = {
            passives  = {},
            selectors = "SelectSpells(2fe27baa-b6e7-5864-8a9f-a17cd4ce6a02,1,0,Wizard_3_Savant)",
        },
        [14] = {
            passives  = { "Evoker_14_Overchannel" },
        },
        [15] = {
            passives  = {},
            selectors = "SelectSpells(20a2907b-0f95-52ab-987c-1067a2144a49,1,0,Wizard_3_Savant)",
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = {},
            selectors = "SelectSpells(b1d357e4-9878-50f0-97a2-66a7cd811c74,1,0,Wizard_3_Savant)",
        },
        [18] = {
            passives  = {},
        },
        [19] = {
            passives  = {},
        },
        [20] = {
            passives  = {},
        },
    },
}

M.subclasses["FeyWanderer"] = {
    parent = "Ranger",
    levels = {
        [15] = {
            passives  = { "FeyWanderer_15_MistyWanderer" },
        },
    },
}

M.subclasses["Fiend"] = {
    parent = "Warlock",
    levels = {
        [14] = {
            passives  = { "Fiend_14_HurlThroughHell" },
            boosts    = "ActionResource(HurlThroughHellCharge,1,0)",
        },
    },
}

M.subclasses["FourElements"] = {
    parent = "Monk",
    levels = {
        [17] = {
            passives  = { "FourElements_17_ElementalEpitome" },
        },
    },
}

M.subclasses["GlamourCollege"] = {
    parent = "Bard",
    levels = {
        [12] = {
            passives  = {},
        },
        [14] = {
            passives  = { "Glamour_14_UnbreakableMajesty" },
        },
    },
}

M.subclasses["GloomStalker"] = {
    parent = "Ranger",
    levels = {
        [15] = {
            passives  = { "GloomStalker_15_ShadowyDodge" },
        },
    },
}

M.subclasses["Glory"] = {
    parent = "Paladin",
    levels = {
        [15] = {
            passives  = { "Glory_15_GloriousDefense" },
        },
        [20] = {
            passives  = { "Glory_20_LivingLegend" },
        },
    },
}

M.subclasses["GraveDomain"] = {
    parent = "Cleric",
    levels = {
        [17] = {
            passives  = { "GraveDomain_17_KeeperOfSouls" },
        },
    },
}

M.subclasses["GreatOldOne"] = {
    parent = "Warlock",
    levels = {
        [14] = {
            passives  = { "GreatOldOne_14_CreateThrall" },
        },
    },
}

M.subclasses["Hellspeaker"] = {
    parent = "Illrigger",
    levels = {
        [11] = {
            passives  = {},
        },
        [13] = {
            passives  = { "Hellspeaker_13_SlipperyPloy" },
        },
        [15] = {
            passives  = { "Hellspeaker_15_QuidProQuo" },
        },
        [18] = {
            passives  = { "HellSpeaker_11_Incontrovertible" },
        },
    },
}

M.subclasses["HighRoller"] = {
    parent = "Gunslinger",
    levels = {
        [14] = {
            passives  = { "HighRoller_14_DoubleOrNothing" },
        },
    },
}

M.subclasses["Hunter"] = {
    parent = "Ranger",
    levels = {
        [15] = {
            passives  = { "Hunter_15_SuperiorHuntersDefense" },
        },
    },
}

M.subclasses["IllusionSchool"] = {
    parent = "Wizard",
    levels = {
        [13] = {
            passives  = {},
            selectors = "SelectSpells(3061c40e-615f-575b-90ce-14b07cbe1189,1,0,Wizard_3_Savant)",
        },
        [14] = {
            passives  = { "Illusionist_14_IllusoryReality" },
        },
        [15] = {
            passives  = {},
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = {},
            selectors = "SelectSpells(1c60118d-69f5-515f-9d14-122345edb8e7,1,0,Wizard_3_Savant)",
        },
        [18] = {
            passives  = {},
        },
        [19] = {
            passives  = {},
        },
        [20] = {
            passives  = {},
        },
    },
}

M.subclasses["KnowledgeDomain"] = {
    parent = "Cleric",
    levels = {
        [17] = {
            passives  = { "KnowledgeDomain_17_DivineForeknowledge" },
        },
    },
}

M.subclasses["LifeDomain"] = {
    parent = "Cleric",
    levels = {
        [17] = {
            passives  = { "LifeDomain_17_SupremeHealing" },
        },
    },
}

M.subclasses["LightDomain"] = {
    parent = "Cleric",
    levels = {
        [17] = {
            passives  = { "LightDomain_17_CoronaOfLight" },
        },
    },
}

M.subclasses["LoreCollege"] = {
    parent = "Bard",
    levels = {
        [12] = {
            passives  = {},
        },
        [14] = {
            passives  = { "PeerlessSkill" },
        },
    },
}

M.subclasses["Mercy"] = {
    parent = "Monk",
    levels = {
        [17] = {
            passives  = { "Mercy_17_HandOfUltimateMercy" },
        },
    },
}

M.subclasses["MoonCollege"] = {
    parent = "Bard",
    levels = {
        [12] = {
            passives  = {},
        },
        [14] = {
            passives  = { "MoonCollege_12_EventidesSplendor" },
        },
    },
}

M.subclasses["NecromancySchool"] = {
    parent = "Wizard",
    levels = {
        [13] = {
            passives  = {},
            selectors = "SelectSpells(fa7d808b-aef3-59a4-a554-c95d31f10051,1,0,Wizard_3_Savant)",
        },
        [14] = {
            passives  = { "Necromancer_14_DeathsMaster" },
        },
        [15] = {
            passives  = {},
            selectors = "SelectSpells(1c4e9987-2425-53e4-b6c1-b53bfbb69f1e,1,0,Wizard_3_Savant)",
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = {},
            selectors = "SelectSpells(47cc3250-fd86-5eba-820a-ebb9f276243c,1,0,Wizard_3_Savant)",
        },
        [18] = {
            passives  = {},
        },
        [19] = {
            passives  = {},
        },
        [20] = {
            passives  = {},
        },
    },
}

M.subclasses["NobleGenies"] = {
    parent = "Paladin",
    levels = {
        [15] = {
            passives  = { "NobleGenies_15_ElementalRebuke" },
        },
        [20] = {
            passives  = { "NobleGenies_20_NobleScion" },
        },
    },
}

M.subclasses["OccultistGuild"] = {
    parent = "MonsterHunter",
    levels = {
        [13] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,3)",
            selectors = "SelectSpells(80c6b070-c3a6-4864-84ca-e78626784eb4,1,1,EldritchKnightAbjEvo)",
        },
        [15] = {
            passives  = { "OccultistGuild_15_SpellbreakerFocus" },
            selectors = "SelectSpells(80c6b070-c3a6-4864-84ca-e78626784eb4,1,1,EldritchKnightAbjEvo)",
        },
        [17] = {
            passives  = {},
            selectors = "SelectSpells(80c6b070-c3a6-4864-84ca-e78626784eb4,1,1,EldritchKnightAbjEvo)",
        },
        [18] = {
            passives  = { "OccultistGuild_18_ArcaneNemesis" },
        },
        [19] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,3)",
            selectors = "SelectSpells(80c6b070-c3a6-4864-84ca-e78626784eb4,1,1,EldritchKnightAbjEvo)",
        },
        [20] = {
            passives  = {},
            selectors = "SelectSpells(80c6b070-c3a6-4864-84ca-e78626784eb4,1,1,EldritchKnightAbjEvo)",
        },
    },
}

M.subclasses["OpenHand"] = {
    parent = "Monk",
    levels = {
        [17] = {
            passives  = { "OpenHand_17_QuiveringPalm" },
        },
    },
}

M.subclasses["Painkiller"] = {
    parent = "Illrigger",
    levels = {
        [7] = {
            passives  = {},
        },
        [13] = {
            passives  = { "Painkiller_13_ByTheThroat" },
        },
        [15] = {
            passives  = { "Painkiller_15_Deathstrike" },
            boosts    = "ActionResource(IllriggerDeathstrike,5,0)",
        },
        [17] = {
            passives  = {},
            boosts    = "ActionResource(IllriggerDeathstrike,1,0)",
        },
        [18] = {
            passives  = { "PainKiller_7_DispatersSupremacy" },
        },
    },
}

M.subclasses["PsiWarrior"] = {
    parent = "Fighter",
    levels = {
        [12] = {
            passives  = {},
        },
        [15] = {
            passives  = { "PsiWarrior_12_BulwarkOfForce" },
        },
        [18] = {
            passives  = { "PsiWarrior_TelekineticMaster" },
        },
    },
}

M.subclasses["PurpleDragonKnight"] = {
    parent = "Fighter",
    levels = {
        [12] = {
            passives  = {},
        },
        [15] = {
            passives  = { "Banneret_12_SharedResilience" },
        },
        [18] = {
            passives  = { "Banneret_18_InspiringCommander" },
        },
    },
}

M.subclasses["RuneKnight"] = {
    parent = "Fighter",
    levels = {
        [12] = {
            passives  = {},
        },
        [15] = {
            passives  = { "RuneKnight_12_MasterOfRunes" },
        },
        [18] = {
            passives  = { "RuneKnight_RunicJuggernaut" },
        },
    },
}

M.subclasses["SanguineKnight"] = {
    parent = "Illrigger",
    levels = {
        [7] = {
            passives  = {},
        },
        [13] = {
            passives  = { "SanguineKnight_13_SanguineGift" },
        },
        [15] = {
            passives  = { "SanguineKnight_15_HaemalExchange" },
        },
        [18] = {
            passives  = { "SanguineKnight_7_BloodForBlood" },
        },
    },
}

M.subclasses["ScionThree"] = {
    parent = "Rogue",
    levels = {
        [11] = {
            passives  = {},
        },
        [13] = {
            passives  = { "DeadThree_13_AuraOfMalevolence" },
        },
        [17] = {
            passives  = { "DeadThree_17_DreadIncarnate" },
        },
    },
}

M.subclasses["Shadow"] = {
    parent = "Monk",
    levels = {
        [17] = {
            passives  = { "Shadow_17_CloakOfShadows" },
        },
    },
}

M.subclasses["Shadowmaster"] = {
    parent = "Illrigger",
    levels = {
        [7] = {
            passives  = {},
        },
        [13] = {
            passives  = { "Shadowmaster_7_HellsAssassin" },
        },
        [15] = {
            passives  = { "Shadowmaster_Illrigger_15_DoomedToTheShadows" },
        },
        [18] = {
            passives  = { "Shadowmaster_18_DarkMalediction" },
        },
    },
}

M.subclasses["Soulknife"] = {
    parent = "Rogue",
    levels = {
        [9] = {
            passives  = {},
        },
        [11] = {
            passives  = {},
        },
        [13] = {
            passives  = { "Soulknife_9_PsychicVeil" },
        },
        [17] = {
            passives  = { "SoulKnife_11_RendMind" },
        },
    },
}

M.subclasses["SpellfireSorcery"] = {
    parent = "Sorcerer",
    levels = {
        [11] = {
            passives  = {},
        },
        [14] = {
            passives  = { "Spellfire_11_HonedSpellfire" },
        },
        [18] = {
            passives  = { "SpellfireSorcery_18_CrownOfSpellfire" },
        },
    },
}

M.subclasses["Spellslinger"] = {
    parent = "Gunslinger",
    levels = {
        [13] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,2,3)",
            selectors = "SelectSpells(22755771-ca11-49f4-b772-13d8b8fecd93,1,1,EldritchKnightAbjEvo)",
        },
        [14] = {
            passives  = { "Spellslinger_14_MagicBullet" },
            selectors = "SelectSpells(22755771-ca11-49f4-b772-13d8b8fecd93,1,1,EldritchKnightAbjEvo)",
        },
        [16] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,3)",
            selectors = "SelectSpells(22755771-ca11-49f4-b772-13d8b8fecd93,1,1,EldritchKnightAbjEvo)",
        },
        [19] = {
            passives  = {},
            boosts    = "ActionResource(SpellSlot,1,4)",
            selectors = "SelectSpells(820b1220-0385-426d-ae15-458dc8a6f5c0,1,1,EldritchKnightAbjEvo)",
        },
        [20] = {
            passives  = {},
            selectors = "SelectSpells(820b1220-0385-426d-ae15-458dc8a6f5c0,1,1,EldritchKnightAbjEvo)",
        },
    },
}

M.subclasses["SwordsCollege"] = {
    parent = "Bard",
    levels = {
        [12] = {
            passives  = {},
        },
        [14] = {
            passives  = { "SwordsCollege_12_MastersFlourish" },
        },
    },
}

M.subclasses["Thief"] = {
    parent = "Rogue",
    levels = {
        [11] = {
            passives  = {},
        },
        [13] = {
            passives  = { "Thief_UseMagicDevice" },
        },
        [17] = {
            passives  = { "Thief_11_ThiefReflexes" },
        },
    },
}

M.subclasses["TotemWarriorPath"] = {
    parent = "Barbarian",
    levels = {
        [14] = {
            passives  = {},
            selectors = "SelectPassives(22222222-2222-2222-2222-222222220001,1,PowerOfTheWilds)",
        },
    },
}

M.subclasses["TransmutationSchool"] = {
    parent = "Wizard",
    levels = {
        [13] = {
            passives  = {},
            selectors = "SelectSpells(0f2cd25a-c4b4-59b8-b8e3-9ed34300b565,1,0,Wizard_3_Savant)",
        },
        [14] = {
            passives  = { "Transmuter_14_MasterTransmuter" },
        },
        [15] = {
            passives  = {},
            selectors = "SelectSpells(a3e8db1f-69b8-548e-877f-e5a9ed456bbd,1,0,Wizard_3_Savant)",
        },
        [16] = {
            passives  = {},
        },
        [17] = {
            passives  = {},
            selectors = "SelectSpells(3d42c7ba-151d-5529-ab52-f5e8d9b6c5bf,1,0,Wizard_3_Savant)",
        },
        [18] = {
            passives  = {},
        },
        [19] = {
            passives  = {},
        },
        [20] = {
            passives  = {},
        },
    },
}

M.subclasses["TrickeryDomain"] = {
    parent = "Cleric",
    levels = {
        [17] = {
            passives  = { "TrickeryDomain_17_ImprovedDuplicity" },
        },
    },
}

M.subclasses["ValorCollege"] = {
    parent = "Bard",
    levels = {
        [12] = {
            passives  = {},
        },
        [14] = {
            passives  = { "BattleMagic" },
        },
    },
}

M.subclasses["Vengeance"] = {
    parent = "Paladin",
    levels = {
        [15] = {
            passives  = { "Vengeance_15_SoulOfVengeance" },
        },
        [20] = {
            passives  = { "Vengeance_20_AvengingAngel" },
        },
    },
}

M.subclasses["WarDomain"] = {
    parent = "Cleric",
    levels = {
        [17] = {
            passives  = { "WarDomain_17_AvatarOfBattle" },
        },
    },
}

M.subclasses["WhiteHat"] = {
    parent = "Gunslinger",
    levels = {
        [14] = {
            passives  = { "WhiteHat_14_GoldStarHero", "WhiteHat_14_GoldStarHero_Surrender" },
        },
    },
}

M.subclasses["WildMagic"] = {
    parent = "Sorcerer",
    levels = {
        [11] = {
            passives  = {},
        },
        [14] = {
            passives  = { "ControlledChaos" },
        },
        [18] = {
            passives  = { "WildMagic_18_TamedSurge" },
        },
    },
}

M.subclasses["WildMagicPath"] = {
    parent = "Sorcerer",
    levels = {
        [14] = {
            passives  = { "WildMagic_14_ControlledSurge" },
        },
    },
}

M.subclasses["WinterWalker"] = {
    parent = "Ranger",
    levels = {
        [15] = {
            passives  = { "WinterWalker_15_FrozenHaunt" },
        },
    },
}

M.subclasses["WorldTreePath"] = {
    parent = "Barbarian",
    levels = {
        [14] = {
            passives  = { "WorldTree_14_TravelAlongTheTree" },
        },
    },
}

M.subclasses["ZealotPath"] = {
    parent = "Barbarian",
    levels = {
        [14] = {
            passives  = { "Zealot_14_RageOfTheGods" },
        },
    },
}

_G.ApotheosisClassExpectations = M
return M
