"""Generate ScriptExtender/Lua/XPTable.lua from Stats/Generated/Data/XPData.txt (2026-10-08).
The XP curve multiplier (XPCurve.lua) needs the level thresholds, which the Script Extender can't read from the
game's XPData. XPTable.START[L] = total XP at which level L starts. Run via regen_all.sh."""
import glob, re, os
root = os.path.join(os.path.dirname(__file__), "..")
src = glob.glob(os.path.join(root, "Public", "*", "Stats", "Generated", "Data", "XPData.txt"))[0]
dst = glob.glob(os.path.join(root, "Mods", "*", "ScriptExtender", "Lua"))[0] + "/XPTable.lua"
inc = {int(m[0]): int(m[1]) for m in re.findall(r'key "Level(\d+)","(\d+)"', open(src).read())}
start, tot = {1: 0}, 0
for lvl in range(1, 20):
    tot += inc[lvl]
    start[lvl + 1] = tot
out = ["-- GENERATED by Scripts/gen_xp_table.py from XPData.txt - do not edit.",
       "-- START[L] = total XP at which level L starts.", "return {"]
out += [f"    [{l}] = {start[l]}," for l in sorted(start)]
out.append("}")
open(dst, "w", newline="\n").write("\n".join(out) + "\n")
print("wrote", dst, "L20 starts at", start[20])
