"""The rules each level-up is checked against (2026-10-05): what a character of each class and subclass gains at every level,
from the rules texts - not from this mod's own progressions, so a test can tell when the mod is wrong.

  tests/bg3/rules/classes.toml           12 core classes, levels 1-20: features, cantrips, prepared spells, slots and the
                                         other table columns. SRD 5.2.1 (CC-BY-4.0) - committed.
  (subclass features: Scripts/gen_subclass_rules.py -> tests/bg3/rules/local/subclasses.toml)

Sources: /mnt/d/Projects/The Oracle/owned_books/srd-cc-v5-2-1.txt and oracle-dm-backend/oracle.db (rules_subclass).
Run: python3 Scripts/gen_rules_tables.py
"""
import json
import os
import re
import sqlite3

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ORACLE = os.environ.get("ORACLE_ROOT", "/mnt/d/Projects/The Oracle")
SRD = os.path.join(ORACLE, "owned_books", "srd-cc-v5-2-1.txt")
DB = os.path.join(ORACLE, "oracle-dm-backend", "oracle.db")
OUT = os.path.join(REPO, "tests", "bg3", "rules")

# the columns after "Class Features" in each SRD class table, in order
COLUMNS = {
    "Barbarian": ["rages", "rage_damage", "weapon_mastery"],
    "Bard": ["bardic_die", "cantrips", "prepared"] + [f"slots_{i}" for i in range(1, 10)],
    "Cleric": ["channel_divinity", "cantrips", "prepared"] + [f"slots_{i}" for i in range(1, 10)],
    "Druid": ["wild_shape", "cantrips", "prepared"] + [f"slots_{i}" for i in range(1, 10)],
    "Fighter": ["second_wind", "weapon_mastery"],
    "Monk": ["martial_arts", "focus_points", "unarmored_movement"],
    "Paladin": ["channel_divinity", "prepared"] + [f"slots_{i}" for i in range(1, 6)],
    "Ranger": ["favored_enemy", "prepared"] + [f"slots_{i}" for i in range(1, 6)],
    "Rogue": ["sneak_attack"],
    "Sorcerer": ["sorcery_points", "cantrips", "prepared"] + [f"slots_{i}" for i in range(1, 10)],
    "Warlock": ["invocations", "cantrips", "prepared", "pact_slots", "pact_slot_level"],
    "Wizard": ["cantrips", "prepared"] + [f"slots_{i}" for i in range(1, 10)],
}


def value(tok):
    if tok == "—":
        return 0
    if re.fullmatch(r"\d+", tok):
        return int(tok)
    return tok


def class_rows(text, cls):
    i = text.find(f"\n{cls} Features\n")
    assert i >= 0, cls
    seg = re.sub(r"\s+", " ", text[i:i + 5000]).replace("+10 ft.", "+10ft").replace("ft.", "ft")
    seg = re.sub(r"\+(\d+) ft", r"+\1ft", seg)
    rows = {}
    for L in range(1, 21):
        m = re.search(rf"(?<![\d+\w]){L} \+([2-6]) (.+?)(?= {L + 1} \+[2-6] | System Reference| Level \d|$)", seg)
        assert m, f"{cls} L{L}"
        toks = m.group(2).split(" ")
        n = len(COLUMNS[cls])
        cols, feats = toks[-n:], " ".join(toks[:-n]).strip()
        row = {"level": L, "proficiency": int(m.group(1)),
               "features": [] if feats in ("", "—") else [f.strip() for f in re.split(r",(?![^()]*\))", feats) if f.strip()]}
        row.update({k: value(v) for k, v in zip(COLUMNS[cls], cols)})
        rows[L] = row
    return rows


def toml_value(v):
    if isinstance(v, list):
        return "[" + ", ".join(toml_value(x) for x in v) + "]"
    if isinstance(v, int):
        return str(v)
    return json.dumps(str(v), ensure_ascii=False)


def main():
    text = open(SRD, encoding="utf-8").read()
    os.makedirs(os.path.join(OUT, "local"), exist_ok=True)
    out = ["# GENERATED by Scripts/gen_rules_tables.py from SRD 5.2.1 (CC-BY-4.0) - every core class, levels 1-20.",
           "# The level-up checks compare the mod against this, never against the mod's own progressions.", ""]
    for cls in COLUMNS:
        for L, row in class_rows(text, cls).items():
            out.append("[[class_level]]")
            out.append(f'class = "{cls}"')
            out += [f"{k} = {toml_value(v)}" for k, v in row.items()]
            out.append("")
    open(os.path.join(OUT, "classes.toml"), "w", encoding="utf-8", newline="\n").write("\n".join(out))

    # subclass features: Scripts/gen_subclass_rules.py (verified against the owned texts)
    print(f"classes.toml: {len(COLUMNS)} classes x 20 levels")


if __name__ == "__main__":
    main()
